### ISSUE TITLE
New database schema

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1]
Before we start converting the project to Vapor, it's going to be worth discussing the database schema. For some background, please [see this document](https://docs.google.com/document/d/1Y8_yLQOn_GA5LhKymqoR5m5a3nWdZI_fGg75YadpJG8/edit?usp=sharing) for project goals, guiding principles, and scope of this conversion project.

I've uploaded [the current database schema](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/wiki/Old-Database-Schema) for reference. This is the database that the [SwiftPM Library](https://swiftpm.co) currently runs on.

![New Database Schema](https://user-images.githubusercontent.com/5180/76216037-cbb2b080-6207-11ea-8129-08fb6b8c5be4.png)

[Editable version](https://app.quickdatabasediagrams.com/#/d/rwpwqR)

## Notes

* I want to change the way that resetting data works. During development, it's useful and necessary to be able to force wipe or force update data for various bits of a package. In the old schema, this was done with the `force_xxxxx_reset` and `force_xxxxx_update` fields. In the new schema, the online metadata is split into a separate table. Wiping online metadata becomes a case of deleting the relevant record from that table, forcing a local metadata re-parse becomes a case of deleting the PackageVersion records. This cleans up both the `force_xxxxx` fields, but also a lot of the confusing `datetime` fields.
* I've changed the way that Swift versions are stored. Originally there was a `swift_versions` table with a join table `package_version_swift_versions` to represent a package version being compatible with multiple versions of Swift. In this new design, it's an array type of enums representing the versions of Swift. The advantage here is that if Swift versions are stored in a database table, it becomes trivial to query packages by Swift version (For example "Show me all packages compatible with Swift 4.2"), I'm just not sure how often we actually need to do that.
* I've excluded some of the error message fields. I'm sure some of these are going to be necessary but I think we should get the structure firmed up before adding those.

**Comment by Mordil** [comment]
This looks great to start with! It is much simpler to reason about and work with compared to the old schema, as you pointed out.

Only feedback I have so far:
- Use `ProjectMetadata` as the table name instead of `GitHubMetadata`, as that leaves it generic for us to all source from GitLab & Bitbucket eventually
  - I think we can keep the `github_username` property on `Author`, and add `gitlab_`/`bitbucket_` eventually so we have a single record for an individual developer
    - This leaves the question of how to associate this data, as some developers might not use the same email for all of the different services (I do for both GitHub & GitLab, but that might not be universal)
    - I don't think this needs to be answered now
- How will we track in the database that a package supports Linux?

**Comment by daveverwer** [comment]
Thank you for the review Nathan!

> Use `ProjectMetadata` as the table name instead of `GitHubMetadata`

Maybe `OnlineMetadata` rather than `ProjectMetadata`? Actually, the fields in the original schema were all prefixed with `online_` so as not to be GitHub specific. I had changed it to `GitHubMetadata` here because honestly, *that's what it is*. There are no packages hosted on any other services. 😬

I think `ProjectMetadata` might be confused with the metadata gathered from the package manifest/repository. This is data coming from an online source rather than a local source.

The only thing I don't like about both of these names compared to `PackageVersion` is the inclusion of the word metadata. It's *all* metadata so why does `OnlineMetadata` have that word, when `PackageVersion` isn't `PackageVersionMetadata`? 😬 

Maybe `HostedRepository`? `OnlineProject`? `GitHubProject`? Naming is hard.

> I don't think this needs to be answered now

I agree. I included the author stuff as I had built out the database for it in the Ruby project but it was never used there, and I think it needs more thought before implementation. I've removed it from the schema for now. We can think about it again if/when we build that feature.

> How will we track in the database that a package supports Linux?

This was one of the first questions brought up when I launched the SwiftPM Library. I included the iOS/macOS/tvOS/watchOS fields because they are right there in the package metadata, but Linux compatibility is not currently supported by Package.swift. There's some good discussion on [this thread](https://github.com/daveverwer/SwiftPMLibrary/issues/33) on the topic. That thread quickly got into the weeds, but it's worth reading.

My view now is the same as it was then. I dislike the idea of trying to *prove* anything about compatibility. The package author is trusted to declare whether the package is compatible with iOS/macOS/tvOS/watchOS so they should be trusted on Linux compatibilitry too. The only thing we lack is a way to indicate it.

I'm still very much in favour of adding an additional metadata file to allow extra information about the package, but like with the package authors above, let's not add the fields to the database until we know what that looks like if/when it happens.

**Comment by daveverwer** [comment]
Here's an updated version of the draft schema too:

![UpdatedSchema](https://user-images.githubusercontent.com/5180/76950786-7f9bf600-6902-11ea-958d-e26375d57630.png)

[Editable version (with comments)](https://app.quickdatabasediagrams.com/#/d/rwpwqR)

**Comment by Mordil** [comment]
> I had changed it to GitHubMetadata here because honestly, that's what it is. There are no packages hosted on any other services. 

I agree with mostly everything you've said, and I think `HostedRepository` is probably a great name for it.

In friendly jest, the one exception is the statement _There are no packages hosted on any other services_.

While I agree the uber majority are found on GitHub - but even with GitLab's lack of comprehensive instance-wide search (compared to GitHub) - I found these two projects _in addition_ to my own 😛:
- [xspm](https://gitlab.com/Pyroh/xspm)
- [gtk-swift](https://gitlab.com/gtk/gtk-swift)
- [RediStack](https://gitlab.com/mordil/RediStack)

As apprehension might start to grow with Microsoft holding so much of the OSS world at this point, and if this tool becomes the defacto standard, we could see others going to other hosted solutions aside from GitHub.

Part of the reason so many use GitHub is the defacto discoverability. This was even discussed directly during the [RediStack SSWG proposal](https://forums.swift.org/t/home-of-sswg-packages/24915/5).

> This was one of the first questions brought up when I launched the SwiftPM Library.
I read all of those threads at the time, and vaguely remember them, but totally forgot that I had done all that 😑 .

I'm 💯 in favor of us defining a metadata file that "extends" Package.swift and adding some sort of `supportsLinux` flag to it and just trusting authors to be good reporters. (We're an index, not a quality check).

All of this looks good to me!

**Comment by daveverwer** [comment]
> I think HostedRepository is probably a great name for it.

I agree, I [changed the diagram to that](https://app.quickdatabasediagrams.com/#/d/rwpwqR).

> In friendly jest, the one exception is the statement There are no packages hosted on any other services.
> 
> While I agree the uber majority are found on GitHub - but even with GitLab's lack of comprehensive instance-wide search (compared to GitHub) - I found these two projects in addition to my own 😛:

Oops, I didn't know you had packages hosted there! 😬 This is all I was looking for, it's on the list for support then.

> I'm 💯 in favor of us defining a metadata file that "extends" Package.swift and adding some sort of supportsLinux flag to it and just trusting authors to be good reporters. (We're an index, not a quality check).

👍

**Comment by finestructure** [comment]
Just wanted to chip in here and mention that over in the `vapor-4` branch I've started to adpot the schema. I've chosen shorter names (I love short names! :) ) and wanted to check if there are some reasons for the ones laid out here that I'm trampeling over. This is all easy enough to change right now.

Here's what I've got:

- `Package` ✅
- `Repository` instead of `HostedRepository`
- `Version` instead of `PackageVersion`
- `Product` instead of `PackageVersionProduct`

The thinking is mainly that it felt a bit redundant to express the relationships in the table names, because in usage `package.versions` and `package.repository` already establish how they relate. I typically only use compound table names (despite being German 😬) for many-to-many join tables.

With respect to `HostedRepository` I felt like `Hosted` isn't really adding much distinction - they're all hosted aren't they?

Does that make sense?

**Comment by daveverwer** [comment]
> * `Repository` instead of `HostedRepository`
> * `Version` instead of `PackageVersion`
> * `Product` instead of `PackageVersionProduct`

I'm certainly happy with all of these. 

> With respect to `HostedRepository` I felt like `Hosted` isn't really adding much distinction - they're all hosted aren't they?

Originally the `HostedRepository` was not going to be the root table, and was just there to hold the stats from the hosted version of the repository on GitHub/GitLab/Bitbucket/etc... (stars, forks, parent_url, etc...). Package was going to be the top-level table which would represent the package itself, and have the product and version tables hanging off it. However, at the current time the `Package` table doesn't hold anything important and so what you're basically doing here is merging `Package` and `HostedRepository` into one table. I think that's fine given that `Package` was such a minimal table, but I wanted to be clear about the initial design and why it was split out.

However, if we are merging it, maybe `Package` is a better name than `Repository`? Yes, that means we'll have a `Package.swift` file representing a database model rather than being an *actual* `Package.swift`, but I checked that all worked fine with the `vapor-3` branch and there were no issues.

So if we merge Package and HostedRepository it becomes:

`Package` -> `Product` -> `Version`

Which makes logical sense to me.

I do think there's some value in having the stats from the online version of the repository split into a separate table, but it's not something I feel very strongly about.

**Comment by finestructure** [comment]
I actually do still have that split and a 1:1 relationship. I was on the fence whether to propose actually merging the two tables but there's one aspect about it that's conceptually nice:

- In the initial "reconcliation" stage we populate `packages`
- in the next stage, "ingestion", we populate `repository` with metadata with pull from Github (Gitlab etc) via API calls
- in the stage after that, "analysis", we populate `versions` and `products`

So each stage aligns with a table and typically only adds data to that table (except for setting status flags and relationship ids). (Maybe "analysis" should therefore be two steps, but that lies ahead still.)

Especially since I've already dealt with the schema setup to keep `packages` and `repositories` separate I'm leaning towards just keeping it that way.

I think where this may become relevant is read access. If we find that we need to join all the time to respond to searches then inlining things might be better. Although it's probably all the same given the cardinalities we'll be dealing with and the bigger problem will be on the side of joining `packages` with `versions` and `products`.

**Comment by daveverwer** [comment]
Ah perfect, I misunderstood and thought that you had merged `Package` and `Repository`. I do prefer keeping them separate too, so we're all on the same page again! 👍

I think in that case, `HostedRepository` makes more sense. I'd expect a `Repository` model to include things from the repository itself, and the distinction that `Hosted` makes is that it's the online version of the repository rather than holding data gleaned from the checked-out version on disk.
