### ISSUE TITLE
Build packages with Swift 5.4

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1038]
I think as we add Swift 5.4, we should deprecate/drop Swift 4.2 (and maybe Swift 5.0 too, meaning we can get rid of the Catalina build machine).

I don't think we need to build with 6 versions of Swift! 😅

**Comment by finestructure** [comment]
* [x] plan work to update build system for 5.4
* infra
	* [x] install Xcode 12.5 on Mac builders
		* [x] mb1
		* [x] mb2
		* [x] spi-prod (can't actually run on spi-prod)
	* ensure `swift:5.4` is published
		- not yet available as of Apr-28
* ensure `spi-prod` doesn't pick up Xcode 12.5 jobs
![xcode-12 5](https://user-images.githubusercontent.com/65520/116403144-81d2c280-a82d-11eb-8599-a1d81d68be1a.png)

	* update tags:
		* [x] add `xcode-12.5` to BS builders
		* [ ] instrument pipeline to request `xcode-12.5` for 5.4 builds
* builder
	* [x] update spi-builder `SwiftVersion.swift` with new values
	* [ ] run test
* front-end
	* [ ] extend trigger
	* [ ] update matrix

**Comment by finestructure** [comment]
We'll need to break up the builder tests and run them across two machines, because they span the full range of builds we're doing and there's no single machine that can do them all: Big Sur machines can't run older Xcode's and Catalina machine can't run 12.5.

**Comment by finestructure** [comment]
A few issues that I've been battling with the last two days:

- we can't run the Linux tests the way I intended, because they require a pre-built docker image (we can't run them via `swift test`, at least not without major fiddling)
- getting a weird test failure running [`BuildMatrixTests. test_5_2_macosSpm` on `spi-prod`](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1225588068)
- `test all` is flakey, perhaps due to `--parallel`. [Failure](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1225588066) but [success](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/1225615602) on re-run.

My hope was to have all 40 builds in `BuildMatrixTests` covered by respective builders as a confirmation for deploying a new builder but that doesn't seem to be feasible.

Might have to scrap this but I really want to avoid having to do manual testing of deployments again.

I'll need to think this through but there may be a way to test the actual binary and image on a branch before merging. That'd be the best way to confirm it's going to work.

**Comment by finestructure** [comment]
Alright, I've got a solution now that'll work without too much fiddling and it'll actually ensure the builder we deploy is passing all builds across the full matrix. Here's a partial run (I still need to add the remaining tests):

https://gitlab.com/finestructure/swiftpackageindex-builder/-/pipelines/295239568

<img width="318" alt="CleanShot 2021-04-30 at 20 23 53@2x" src="https://user-images.githubusercontent.com/65520/116738006-2e5da180-a9f2-11eb-99a4-1f9eaed7a453.png">

It's a bit repetitive to set up but I much prefer that being repetitive once and then it just runs instead of having to exercise those tests manually before each deploy.

**Comment by finestructure** [comment]
There's some cleanup work left to do but the jobs have finally all passed across the whole build matrix:

https://gitlab.com/finestructure/swiftpackageindex-builder/-/pipelines/296053511

![CleanShot 2021-05-03 at 08 43 23@2x](https://user-images.githubusercontent.com/65520/116847887-c5da1480-abeb-11eb-9e52-d4c177e70b9a.png)

**Comment by finestructure** [comment]
I'm pulling the "update the build matrix" point into a new issue so we can close this one here. It's probably going to take a couple of days for the builds to be caught up.
