### ISSUE TITLE
Package page loads for packages with lots of releases are slow

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1072]
There's a performance problem with package pages. Packages that have a large number of releases or products take quite a significant amount of time to load.

For example:

* [LeftPad](https://swiftpackageindex.com/daveverwer/LeftPad) - 3 releases - 170ms
* [Alamofire](https://swiftpackageindex.com/Alamofire/Alamofire) - 67 releases - 722ms
* [Vapor](https://swiftpackageindex.com/vapor/vapor) - 262 releases - 1,480ms
* [fastlane](https://swiftpackageindex.com/fastlane/fastlane) - 483 releases - 1,220ms

and

* [Soto](https://swiftpackageindex.com/soto-project/soto) - 265 libraries - 2,280ms
* [smoke-aws](https://swiftpackageindex.com/amzn/smoke-aws) - 32 libraries - 701ms

It's not a linear scale, as fastlane proves. But certainly, there is a correlation between page speed and the number of products/releases. 

After a quick chat with @finestructure, this isn't as simple as adding indexes! 😬 It's the deserialisation of all version objects that are used to generate the significant versions panel as well and the solution is not trivial.

However, since we only need the significant versions (stable, beta, branch) for the rest of the page, and everything else is just a count, and products are only ever displayed as a count, I wonder if we should limit our deserialisation to only the significant versions, and maybe de-normalise the number of releases, libraries, and executables into the products table and update it during analysis?

**Comment by finestructure** [comment]
This is quite tricky. I've taken the first hurdle of joining `Version` multiple times for the different significant versions. However, the current blocker is that the `pre_release` version might not be present.

In SQL, that translates to 

```sql
LEFT JOIN "versions" AS "pre_release_version" ON ("packages"."id" = "pre_release_version"."package_id" and "pre_release_version"."latest" = 'pre_release')
```

However, this doesn't seem to be expressible with Fluent at this time. The join clause expects this to be an simple expression of the kind `\PreReleaseVersion.$package.$id == \Package.$id`. It doesn't accept composing this together as

```swift
(\PreReleaseVersion.$package.$id == \Package.$id
                         && \PreReleaseVersion.$latest == .preRelease)
```

I'll have to dig in to find out if we extend the syntax. I'd rather not have to drop down to raw SQL here as it would get really brittle with respect to new fields etc.

**Comment by finestructure** [comment]
NB: we cannot do

```sql
LEFT JOIN "versions" AS "pre_release_version" ON "packages"."id" = "pre_release_version"."package_id"
WHERE "pre_release_version"."latest" = 'pre_release'
```

or

```sql
LEFT JOIN "versions" AS "pre_release_version" ON "packages"."id" = "pre_release_version"."package_id"
WHERE ("pre_release_version"."id" IS NULL OR "pre_release_version"."latest" = 'pre_release')
```

because those turn into `INNER` joins. The selection _needs_ to happen in the `ON` clause.

**Comment by finestructure** [comment]
This is going to be quite a large, multi-step task. While I've sort of come up with a plan and 2/3 implementation to improve the performance of the "package show" query, I ended up realising that this can't be done without impacting quite a number of other areas where we're using the same query.

Here's the current state of affairs:

The cause of the slow down is in part the running of the query itself and in part the sending and decoding of data, very roughly half-half according to Instruments. Essentially, we need to both make the query less complex and send less data. It's pretty obvious how to do that but the mechanics of it are fiddly.

The current query driving "package show", `PackageController.PackageResult.query`, or `PR.query`, does the following:
- Query `packages` and join it with `repositories`, loading all fields
- Query `versions` for the selected package, loading all its versions with all fields
- Query `products` for each version of the selected package, loading all their fields
- Query `builds` for each version of the selected package, loading all their fields

So in total we're looking at four queries across five tables, some of which contain columns of considerable size.

Call sites of `PR.query` are
- `PC.badge` (yellow)
- `PC.builds` (purple)
- `PC.maintainerInfo` (green)
- `PC.show` (blue)
- `PC.trigger` (red)
(`PC` is short for `PackageController` here.)

The following image maps these calls onto the relational model of packages `P`, repositories `R`, versions `V`, builds `B`, and products `PR`, with the colours as referenced in the list above.

![INDBD - 32 4270](https://user-images.githubusercontent.com/65520/145009395-a7f3122a-f78f-4f3b-91df-786c44cc1ee9.png)

The "main" and original call site of `PR.query` is `PC.show`. We've (well, pretty much I've 😅) subsequently re-used its query in the other call sites, because it fetches practically all data associated with a package, easily allowing all sorts of computations. For the vast majority of packages that's performant and keeps the implementation simple - no new queries were required.

However the image clearly shows the inefficiencies, some of which have gotten considerably worse since inception, because we've added quite a bit more data to some of the tables, for example release notes and dependency info. So what used to be a somewhat inefficient fetch has gotten worse because we added "heavy" columns that mostly aren't used.

The image also clearly shows that `PR.query` isn't the best place to start. It's what's driving the outer, blue query and changing it impacts the other queries to some degree. I.e. if we trim the blue query to what it actually needs (which is considerably less than what the current blue zone encompasses) we'll invariably intersect with the other calls' requirements, i.e. their colour zones.

And that means that if we optimise the blue zone we'll end up trimming data from some of the other zones due to different data requirements, making the query driving the blue zone unusable for them. There will still be some cases (for instance `maintainerInfo`) where we could perhaps re-use the "trimmed blue zone query" with only minor inefficiencies even after optimisation but generally the blue zone query will cease to be a superset of the others.

Instead, the better approach is to refine their queries first in order to make them independent of the query populating the blue zone. After that, we can tweak `PR.query` to get a better matching blue zone.

I've started mapping out the actual data requirements for each call site and will then either add list of tasks to this issue or break them out into separate issues.

**Comment by finestructure** [comment]
### Data slices
The data that's actually required from each of the five queries is as follows:
(`PC` = `PackageController`, `PR` = `PackageResult`, `R` = `Repository`, `P` = `Package`, `V` = `Version`, `B` = `Build`)
- `PC.badge`  → `Badge`
	- `Build` for significant versions
		- `B.platform`
		- `B.status`
		- `B.swiftVersion`
- `PC.builds` → `BuildIndex.Model`
	- `V.packageName` for default version
	- `R.owner`
	- `R.name`
	- `Build` for significant versions
		- `B.platform`
		- `B.status`
		- `B.swiftVersion`
- `PC.maintainerInfo` → `MaintainerInfoIndex.Model`
	- `V.packageName` for default version
	- `R.owner`
	- `R.name`
- `PC.show` → `PackageShow.Model`
	- `PR.activity()`
		- `P.url`
		- `R.lastPullRequestClosedAt`
		- `R.openIssues`
		- `R.openPullRequests`
		- `R.lastIssueClosedAt`
		- `R.lastPullRequestClosedAt`
	- `PR.history()`
		- `P.url`
		- release count: count of all versions for a given package where `V.reference` is a release. This filter is very difficult to express in SQL. We're decoding the reference (an enum with associated values) into a `SemanticVersion` and filtering on its `isStable` property. We _must_ load at least all `references` of a given package to compute this.
		- `R.defaultBranch`
		- `R.firstCommitDate`
		- `R.commitCount`
	- `PR.productCounts()`
		- library + executable count: these are counts of products of type `library` and `executable` of the `defaultVersion`, i.e. _only_ the version where `latest == .defaultVersion`. The query is possible to express in SQL but it's going to be simpler to just fetch the `type` field only and count them client side. There are less than 10% of executables across all products so fetching all and filtering in Swift is much easier than crafting an SQL query with two nested counts at no significant loss of performance.
- `PC.trigger`
	- `V.id` for significant versions

**Comment by finestructure** [comment]
Plan:

- [ ] individual queries instead of reusing `PC.show` ("blue") query for
  - [ ] `badge`
  - [ ] `builds`
  - [ ] `maintainerInfo`
  - [ ] `trigger`
- [ ] rework `show` query to avoid pulling in the full "blue" zone
  - [ ] joins with significant versions
  - [ ] release count query
  - [ ] product count query

**Comment by finestructure** [comment]
I'm not done cleaning up yet but the wiring is in place. We'll see a dramatic improvement after these changes also and especially for the package page:

```
┌──────────────────────────────┐   ┌──────────────────────────────┐
│                              │   │                              │
│2.53.3                        │   │this branch:                  │
│                              │   │                              │
│Alamofire-package             │   │Alamofire-package             │
│-----------------             │   │-----------------             │
│Count:     100                │   │Count:     100                │
│Average:   0.121s             │   │Average:   0.069s             │
│Median:    0.119s             │   │Median:    0.069s             │
│Min:       0.112s             │   │Min:       0.063s             │
│Max:       0.169s             │   │Max:       0.086s             │
│Std dev:   0.008s             │   │Std dev:   0.003s             │
│90% Pctl:  0.127s             │   │90% Pctl:  0.073s             │
│                              │   │                              │
│soto-package                  │   │soto-package                  │
│------------                  │   │------------                  │
│Count:     100                │   │Count:     100                │
│Average:   2.652s             │   │Average:   0.102s             │
│Median:    2.647s             │   │Median:    0.102s             │
│Min:       2.606s             │   │Min:       0.095s             │
│Max:       2.751s             │   │Max:       0.132s             │
│Std dev:   0.028s             │   │Std dev:   0.005s             │
│90% Pctl:  2.689s             │   │90% Pctl:  0.108s             │
│                              │   │                              │
│                              │   │                              │
└──────────────────────────────┘   └──────────────────────────────┘
```

I.e. after this, Soto will load faster than Alamofire does now (a ~26x improvement from 2.7s to 100ms) and Alamofire will load in 70ms instead of 120ms.
