### ISSUE TITLE
Use full owner name when building package collections

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1160]
We should use the full owner name here rather than the username.

![Screenshot 2021-06-08 at 13 03 18@2x](https://user-images.githubusercontent.com/5180/121181452-eedc6d80-c859-11eb-936a-8251063e790b.png)

**Comment by at-syot** [comment]
Hi, i'm interesting to work on this issue.

**Comment by finestructure** [comment]
That's great, let us know if you've got any question getting set up with the project and tests!

**Comment by finestructure** [comment]
This issue (and its cousin #1159) is actually not that simple, because `PackageCollection.generate` handles (via `filter`) both author and package urls based collection generation.

Also, `Packages by "author"` can be multiple authors in case of package lists.

We can use the fact that the query inside `PackageCollection.generate`  already joins with `$repositories`, i.e. we have access to `ownerName` via `package.repository?.ownerName` (or something similar). One thing to watch out for is that `ownerName` can be `nil` and we'd have to default to just `owner` in that case.

What I'd do to tackle this is package up the inputs for `PackageCollection.init` into a tuple with the result of the first closure after `query.all()`. I.e. implement something like this:

```swift
func authorName(packages: [App.Package]) → String {
  let names = packages.map { package.repository.ownerName ?? package.repository.owner }
  switch names.count {
    case 0:
      // shouldn't be possible really
      return ""
    case 1:
      return names.first!
    case 2:
      return names.joined(separator: " and ")
    case 3...:
      return "multiple authors"
  }
}
```

and then something like this:

```swift
        return query.all()
            .map { versions in
                // Multiple versions can reference the same package, therefore
                // we need to group them so we don't create duplicate packages.
                // This requires App.Package to be Hashable and Equatable.
                Dictionary(grouping: versions, by: { $0.package })
                    .sorted(by: { $0.key.url < $1.key.url })
            }
            .map { packageToVersions in
              (packageToVersions, authorName(packages: packageToVersions.keys))
            }
            .map { (packageToVersions, authorName) in 
              let packages = packageToVersions.compactMap {
                  Package.init(package: $0.key,
                               prunedVersions: $0.value,
                               keywords: keywords)
              }
              return (packages, autorName)
            }
            .map { (packages, authorName) in
                let overview =
                return PackageCollection.init(
                    name: collectionName,
                    overview: overview ?? "A collection of packages authored by \() from the Swift Package Index",
                    keywords: keywords,
                    packages: packages,
                    formatVersion: .v1_0,
                    revision: revision,
                    generatedAt: Current.date(),
                    generatedBy: authorName.map(Author.init(name:)))
            }
```

(NB: I haven't actually compiled this, so this will almost certainly need tweaking!)

While this looks pretty awkward here due to having to pass through `authorName`, async/await will clean this up considerably turning it into straightforward imperative code.

It might be worth just waiting for that to be honest.

**Comment by daveverwer** [comment]
That's a great point @finestructure. I was thinking about this purely in terms of owner collections but you're right that this gets much more complex with generic collections.

I wonder if there's an easier way to think about this. 

I'm not sure that making the title consist of all author names makes sense outside of author collections though, maybe the collections should just have a title and a description/overview property. That way, just the single author can be passed in for author collections and we can do something different when we get to arbitrary collections.

That would make this change trivial, and when we implement more types of collections they don't need to all have the same information in the title.

**Comment by finestructure** [comment]
Yeah, that would make it easier but still a bit fiddly with the `map`s without async/await and just the switching on owner/list collections.

I.e. you save writing the `authorName` func (which isn't that complicated tbh) but the rest still needs doing unfortunately.

**Comment by daveverwer** [comment]
Even if it doesn't make it simpler, I think we should use the approach of pushing the title and overview in from outside the generator so we have more flexibility with what we use.

**Comment by finestructure** [comment]
Note we can't really move it out of the generator unless we introduce a second query. Outside the generator we don't have the info for the additional details, whereas the generator does. It's just that without async/await it's a little "ugly" and more complicated to get at it.

**Comment by at-syot** [comment]
What if we change the generator func from static to normal func, and introduce new helper (new query, single purpose) func that take care for (owner_name, overview).

**Comment by finestructure** [comment]
If I understand correctly that's the scenario I was referring to with "unless we introduce a second query". Since we're already pulling in the data we need, it's really just a matter of going through the slightly unwieldy gymnastics of accessing it inside `generate`.

We should avoid making the extra request here, because we've got the data already and the slightly clumsy access will disappear once we switch to async/await (and it's not all that bad, really).
