### ISSUE TITLE
Package collection.json differs from author page

### ISSUE THREAD

**Issue by stephencelis** [SwiftPackageIndex/SwiftPackageIndex-Server#1162]
Really awesome to see integration with Xcode 13! Congrats! 😄

First thing I did was load up the Point-Free collection, which seems to have a discrepancy in which packages are surfaced when compared to the Point-Free author page.

- <https://swiftpackageindex.com/pointfreeco/collection.json> (9 packages)
- <https://swiftpackageindex.com/pointfreeco> (18 packages)

I'm not sure if this is a caching thing or a bug, and didn't find a similar issue, so wanted to surface it in case it's something to look into!

**Comment by finestructure** [comment]
Thanks Stephen, we're excited to see it as well! 😊

There are a few validations around targets and products and it's possible that versions and ultimately packages get "compact mapped" out of the list if they don't validate. I suspect that either the validation is too strict or we are missing some data for some of your packages.

We'll take a look, thanks for reporting it!

**Comment by finestructure** [comment]
As suspected, taking `Overture` as an example which probably applies to the other omissions as well, the issue is that the product type is `nil` for all versions. This should be one of `.library(.automatic|.dynamic|.static)`, `.executable`, or `.test`.

Looks like there's either a parsing error or for some reason our recent reprocessing of versions didn't update these versions. The version (`61385B1D-56EE-4825-A6DC-2351FC1034F6`) itself has the correct `updated_at` of `2021-06-09 05:16:29.558642+00` from when I reprocessed but its product is old: 

![CleanShot 2021-06-09 at 09 19 51@2x](https://user-images.githubusercontent.com/65520/121310679-e8a2cb80-c903-11eb-88be-5e25f7da0c88.png)

**Comment by finestructure** [comment]
I've reprocessed affected packages and the collection now works fine on staging. Prod should be done soon, I'll update this issue when it is.

![CleanShot 2021-06-09 at 12 07 22@2x](https://user-images.githubusercontent.com/65520/121335940-59091700-c91b-11eb-953e-709598fab9fd.png)

**Comment by finestructure** [comment]
This is now done on prod. Note that there might be some residual caching at work - we've seen some packages return the updated values while others have not. Please re-open if this isn't working as expected by tomorrow!

Thanks again for reporting it!

**Comment by stephencelis** [comment]
Thanks Sven!
