### ISSUE TITLE
Order packages on author's page alphabetically

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1163]
combine-schedulers should be first etc

<img width="1174" alt="CleanShot 2021-06-09 at 08 56 33@2x" src="https://user-images.githubusercontent.com/65520/121307778-a75cec80-c900-11eb-97a9-19b9e5acdfce.png">

**Comment by Sherlouk** [comment]
I feel to do this we'd want to start adding extra context with regards to the popularity of a package?

Ordering by score makes it easy to find the packages an author is known best for - we don't show stars or other information like that (currently) so feels like it would make it less helpful if a page... at least for me!

**Comment by daveverwer** [comment]
I think the problem with ordering by score is that we don't explain what score packages get and so it can seem like arbitrary ordering. I thnk until we visualise the score or something related to the score, alphabetical probably makes more sense.

**Comment by Sherlouk** [comment]
I'm not against ordering alphabetically - but would also like to see it come along with some extra contextual data so I can more easily scan the big packages from the smaller ones.

Stars should be an easy solution for this, in my opinion

**Comment by selichter** [comment]
I can take this one. I'll start with just ordering them, what are everyone's thoughts on something like this (though styled better) for exposing a bit more data? Is it enough context?

<img width="1174" alt="121307778-a75cec80-c900-11eb-97a9-19b9e5acdfce" src="https://user-images.githubusercontent.com/9971367/127091336-3c865a2d-5c4e-4836-981f-bb1a1288777c.png">

**Comment by finestructure** [comment]
I think that’d go a long way to make that list easier to “parse” 👍

**Comment by daveverwer** [comment]
This looks great Sarah, thank you. I'd like to see this go forward into a PR.

The only thing I'd say just to set some expectations is that when we work on the display of keyword terms, author results, and package results this page might go under a bit of a re-design and I can't promise these stars will end up in exactly the same place as they are in this screenshot, but having them there as a starting point is great.

**Comment by daveverwer** [comment]
Scratch that. I should be honest. 😬

I didn't reply to @Sherlouk's original comment about stars as I knew I'd need to write a lot to explain myself, and I was busy at the time. While I agree that this is the easiest thing we could do, I don't think relying *only* on stars is a great way to distinguish packages on this page or anywhere.

Yes, they indicate popular packages, but it removes so much of the work we have done to surface the metadata we collect. Is a package terrible if it only has three stars? No. Is a package with 1,000 stars better than a package with 50? Not necessarily. Is a package that got 500 stars over ten solid, reliable years of development and maintenance the same as a package that got 500 stars because the author has thousands of Twitter followers? 

Now, I know that all the packages are from the same author on this page, so it does make a *little* more sense to use stars here. But, as soon as we start to use stars as the only metric we display, it lessens all the other work we've done and allows us to use this page as a reason to display only stars somewhere else in the future. "We did it on the package author page. Why not here too?"

The solution here is to display our package "grades" idea against these packages. Our current thinking is that a package will have a quality and a maintenance grade. Quality based on metrics gathered from code, tests, compatibility, etc. and maintenance gathered from time in development, number of releases, number of contributors, regularity of releases, etc. I'm not sure stars will really factor into either, but if it does, it'll be 5% of one grade, not the primary stat.

I would still be happy to merge this, as it's a better indicator than nothing at all, and we do not have the work on the package grades yet, but I also wanted to write down why I'm not a fan of relying on stars.

**Comment by daveverwer** [comment]
Actually. I should be double super honest. 😂

> I would still be happy to merge this, as it's a better indicator than nothing at all, and we do not have the work on the package grades yet, but I also wanted to write down why I'm not a fan of relying on stars.

I'd rather not merge it with only stars displayed. However, I would be happy to if the consensus is that we should.

**Comment by daveverwer** [comment]
There's no more honesty coming. I'm done 😂
