### ISSUE TITLE
Widen keyword search

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1193]
Via https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/1190#discussion_r658497753

The initial keyword search implementation is doing simple `"keyword" = 'test'` filtering with LIMIT 1 when searching for `test`.

We'll want to also match `unit-testing`, changing that to `"keyword" like '%test%'` with some limit on the results, say `LIMIT 3`. When we do that we'll also need to `DISTINCT` the results (because the `UNNEST` is generating lots of duplicates).

More importantly, we'll need to define a sort order of partial keyword matches. I'm thinking something like

1. exact match
2. partial matches `%test%` ordered by number of occurrences, alphabetically

**Comment by finestructure** [comment]
Follow-up to #1179

**Comment by daveverwer** [comment]
Just a quick note on this. Number 4 is already done. The multi-result display is even tested in the snapshots:

<img width="1200" alt="test_SearchShow desktop" src="https://user-images.githubusercontent.com/5180/154267904-92963900-25b3-4a6f-8b38-a3179489dfba.png">
.

**Comment by finestructure** [comment]
Re 1, I meant to add example queries. Here's the current subquery for keyword search:

```sql
-- 2.57.6 (Feb 16 2022) single result query
SELECT 
  'keyword' AS "match_type", "keyword", NULL AS "package_id", NULL AS "package_name", NULL AS "repo_name", 
  NULL AS "repo_owner", NULL AS "score", NULL AS "summary", NULL AS "stars", NULL AS "license", 
  NULL::TIMESTAMP AS "last_commit_date", NULL::TIMESTAMP AS "last_activity_at" 
FROM 
  "search",
  UNNEST("keywords") AS "keyword" 
WHERE "keyword" = 'test' LIMIT 1
```

This returns a single row IFF there's an exact keyword match.

If we widen the `WHERE` clause as follows:

```sql
-- multi result query
SELECT 
  'keyword' AS "match_type", "keyword", NULL AS "package_id", NULL AS "package_name", NULL AS "repo_name", 
  NULL AS "repo_owner", NULL AS "score", NULL AS "summary", NULL AS "stars", NULL AS "license", 
  NULL::TIMESTAMP AS "last_commit_date", NULL::TIMESTAMP AS "last_activity_at" 
FROM 
  "search",
  UNNEST("keywords") AS "keyword" 
WHERE "keyword" ilike '%test%' LIMIT 10
```

we'd get the following results:

<img width="619" alt="CleanShot 2022-02-16 at 15 06 54@2x" src="https://user-images.githubusercontent.com/65520/154281149-c2da6fd2-6395-41ea-8854-61a8226d14ce.png">

In order for this to be useful, we need to sort the results, ideally in such a way that an exact match is first automatically without having to give that special consideration. Levenshtein distance between the row's result and the search term should do that.

**Comment by daveverwer** [comment]
I did some investigation on this today and have good news! It’s really simple and we have several options on how to do it. 🚀

### Search ordering

I tried two different methods of word similarity. The Postgres `levenshtein` function and the `similarity` and `metaphone` functions combined. Here’s an example:

```sql
SELECT DISTINCT
	keyword,
	levenshtein('image', keyword) AS levenshtein_distance,
	similarity(metaphone(keyword, 15), metaphone('image', 15)) AS similarity
FROM
	search,
	UNNEST(keywords) AS keyword
WHERE
	keyword ilike '%image%'
ORDER BY
	levenshtein_distance asc;
```

The `metaphone` is configured here with 15 significant characters. I ran several tests with both correctly spelled and misspelled search terms and `levenshtein` came out better or equal every time. I think we should use `levenshtein` for ordering. It’s also super simple.

### Matching

I also looked into fuzzy matching while I was at it and we have some easy options here too. This may be better as part of a different PR/feature as they would also work well on standard package name/summary search.

We could use trigrams to fuzzy match on all these searches giving us good support for recovering from typos and misspellings, as well as broadening out our search scope a bit.

Using the `%` operator will use trigram-based matching, so taking that query above:

```sql
SELECT DISTINCT
	keyword,
	levenshtein('image', keyword) AS levenshtein_distance
FROM
	search,
	UNNEST(keywords) AS keyword
WHERE
	keyword % 'image'
ORDER BY
	levenshtein_distance asc;
```

This gives us some really great keyword results:

<img width="329" alt="Screenshot 2022-02-16 at 22 03 35@2x" src="https://user-images.githubusercontent.com/5180/154365963-565dd5b4-b5dd-4440-a0ca-4592f75a8a89.png">

<img width="341" alt="Screenshot 2022-02-16 at 22 03 56@2x" src="https://user-images.githubusercontent.com/5180/154365971-62d99952-3284-40f7-a7f1-5923b5ecb5ad.png">

Some search terms are less interesting, but it still gets everything right at the top of the list:

<img width="331" alt="Screenshot 2022-02-16 at 22 04 41@2x" src="https://user-images.githubusercontent.com/5180/154365987-e51a2e3a-772d-4f07-8760-31d9059d5059.png">

We may also want some [custom indexes for this type of matching](https://www.postgresql.org/docs/13/pgtrgm.html#id-1.11.7.40.8).

As I say, we may want to do the trigram fuzzy matching across all search types as part of a separate feature but it’s something we’ll want to do at some point.

### Search query

So, here’s what we need, either with or without the `%` in the `WHERE` clause:

```sql
SELECT DISTINCT
	'keyword' AS "match_type",
	"keyword",
	NULL AS "package_id",
	NULL AS "package_name",
	NULL AS "repo_name",
	NULL AS "repo_owner",
	NULL AS "score",
	NULL AS "summary",
	NULL AS "stars",
	NULL AS "license",
	NULL::TIMESTAMP AS "last_commit_date",
	NULL::TIMESTAMP AS "last_activity_at",
	levenshtein("keyword", 'test') as "levenshtein_distance"
FROM
	"search",
	UNNEST("keywords") AS "keyword"
WHERE
	"keyword" % 'test'
ORDER BY
	levenshtein_distance ASC;
LIMIT 15;
```

Unfortunately, we do need the `ORDER BY` field in the query so we’ll need to expand the `UNION` to cope with that.

**Note:** We need to install up to two extensions into our Postgres image. The Levenshtein distance and Similarity functions need the `fuzzystrmatch` extension. This needs executing once:

```sql
CREATE EXTENSION fuzzystrmatch;
```

For trigrams we need the `pg_trgm` extension which can be installed with:

```sql
CREATE EXTENSION pg_trgm;
```

However, I don’t this may not need executing because when I executed on my prod database dump, it was already installed.

**Comment by finestructure** [comment]
That's great, thanks for taking a look at that!

Great find also on that trigram matching operator. I like this a lot and I think it'd be even easier to use than patching up the search term with `%` on either end. I'll stick it in just to see how it goes.

The reason that already worked for you is because we've run `CREATE EXTENSION pg_trgm` way back in migration 002. That also means it'll be very easy to do the same for `fuzzystrmatch`. I'm guessing it is a built-in extension that just needs activating this way or you'd have mentioned having to install something else.

I think the only other thing to do is to check query cost via `EXPLAIN ANALYZE` and to check if we need any indexes to make this as fast as possible.

**Comment by finestructure** [comment]
Some notes regarding performance:

### Query performance (partial query, just the different operators)
- `=`
```
Limit  (cost=0.00..799.73 rows=1 width=336) (actual time=8.660..28.633 rows=1 loops=1)
Execution Time: 28.863 ms
```

- `ILIKE`
```
Limit  (cost=927.95..927.96 rows=1 width=336) (actual time=35.147..35.152 rows=10 loops=1)
Execution Time: 35.459 ms
```

- `%`
```
Limit  (cost=927.95..927.96 rows=1 width=336) (actual time=46.972..46.977 rows=10 loops=1)
Execution Time: 55.499 ms
```

Links
- making sure index is used in order by: https://stackoverflow.com/a/47516344/1444152
- operators & indexes for similarity search: https://www.postgresql.org/docs/13/pgtrgm.html

### Levenshtein ORDER BY performance (partial query)
- `ILIKE` + `levenshtein`
```
Limit  (cost=949.35..949.35 rows=1 width=340) (actual time=40.480..40.486 rows=10 loops=1)
Execution Time: 40.866 ms
```

- `%` + `levenshtein`
```
Limit  (cost=949.35..949.35 rows=1 width=340) (actual time=50.227..50.231 rows=10 loops=1)
Execution Time: 48.649 ms
```

- can't actually use indexes here, because `keyword` is an "on-the-fly" field from `UNNEST("keywords") AS "keyword"`
- `similarity` seems to be about as fast as `levenshtein`

**Comment by finestructure** [comment]
### Full query with Levenshtein (i.e. above partial query in full query context)
- `=` (just as a baseline, this effectively ignores `ORDER BY`)
```
Append  (cost=0.00..1429.05 rows=23 width=276) (actual time=26.065..29.894 rows=22 loops=1)
Execution Time: 30.800 ms
```

- `ILIKE`
```
Append  (cost=0.00..1429.05 rows=23 width=276) (actual time=47.755..53.634 rows=31 loops=1)
Execution Time: 47.671 ms
```

- `%`
```
Append  (cost=0.00..1429.05 rows=23 width=276) (actual time=54.482..60.196 rows=31 loops=1)
Execution Time: 56.357 ms
```

The execution time jitters quite a bit (easily ±10-15%) but the hierarchy of the ones I've pasted in is representative.

**Comment by finestructure** [comment]
So this will impact search quite a bit, percentage wise. Not a huge deal at this level but we have to keep in mind that we'll probably get the same hit in addition for the author subquery.

We can't improve on the keywords search via an index due to the way it's operation on the `UNNEST` "dynamic table". There might be a workaround for that but it's not obvious.

We might be able to add an index for the author subquery as it directly targets the `repo_owner` field.

**Comment by daveverwer** [comment]
> I'm guessing it is a built-in extension that just needs activating this way or you'd have mentioned having to install something else.

Yes. It's built-in. Just the command needs running.
