### ISSUE TITLE
Bug with packages from Aben/rushairer

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1233]
Something very strange is going on with these packages. As reported [here](https://github.com/SwiftPackageIndex/PackageList/pull/1252#issuecomment-891517597) by Aben, his package [ZoomableImageView](https://swiftpackageindex.com/rushairer/ZoomableImageView) is not showing up in search:

<img width="872" alt="Screenshot 2021-08-03 at 08 44 40@2x" src="https://user-images.githubusercontent.com/5180/127977628-02a8a9c6-9c99-4dc7-95be-b34729adafca.png">

I checked, and it is definitely in the `search` view, and everything looks good with the database from a quick check:

<img width="839" alt="Screenshot 2021-08-03 at 08 37 51@2x" src="https://user-images.githubusercontent.com/5180/127976730-34842b4e-3cc5-490f-accb-6ea001b96562.png">

Then, there's something else. I noticed three packages in the database, but when I was investigating this before doing the query I had been to the package author page and there were only two packages listed. Sure enough:

<img width="877" alt="Screenshot 2021-08-03 at 08 42 51@2x" src="https://user-images.githubusercontent.com/5180/127977420-2ada3280-d35f-4b15-8dfe-b4f3c3614c9a.png">

and yet:

* [ScreenshotableView](https://swiftpackageindex.com/rushairer/ScreenshotableView)
* [ZoomableImageView](https://swiftpackageindex.com/rushairer/ZoomableImageView)
* [ABWheelPickerModifier](https://swiftpackageindex.com/rushairer/ABWheelPickerModifier)

**Comment by finestructure** [comment]
Looks like we're filtering out results based on missing data. For instance, `ABWheelPickerModifier` is missing from the author page, because it has no description. This gets filtered out here:

```swift
extension PackageInfo {
    init?(package: Package) {
        guard let repoName = package.repository?.name,
              let repoDescription = package.repository?.summary,
              let repoOwner = package.repository?.owner
        else {
            return nil
        }
        ...
```

I believe this is overly strict and we should simply substitute in `""`, which would look as follows:

<img width="748" alt="CleanShot 2021-08-16 at 19 30 20@2x" src="https://user-images.githubusercontent.com/65520/129605196-eb896109-849f-4911-9878-b9a6c2469977.png">

**Comment by finestructure** [comment]
The issue with search is that `package_name` is `NULL`:

<img width="943" alt="CleanShot 2021-08-16 at 19 51 55@2x" src="https://user-images.githubusercontent.com/65520/129607785-213b9562-4c5c-4b3a-a6af-f274584bbd9f.png">

which gets dropped as part of the package search query:

```swift
        return binds.reduce(preamble) { $0.where(haystack, contains, $1) }
            .where(isNotNull(packageName))
            .where(isNotNull(repoOwner))
            .where(isNotNull(repoName))
            .where(searchFilters: filters)
            .orderBy(sortOrder)
            .offset(offset)
            .limit(limit)
```

This is very likely because we're not analysing with 5.5 and the package is 5.5 only. I.e. that should be fixed once we analyse with Swift 5.5 (soon).

We might want to be more lenient here as well but this may have bigger repercussions, so I wouldn't want to fiddle with it unless it's a bigger issue. For instance, even if we allow results with `NULL` here, we may just get weird display issues without package names in other places.

**Comment by finestructure** [comment]
I've got a fix for the first issue, the second I'd leave up to 5.5 analysis to straighten out.

**Comment by rushairer** [comment]
@daveverwer  @finestructure 

https://swiftpackageindex.com/rushairer   ( no ABWheelPickerModifier )

https://swiftpackageindex.com/search?query=rushairer   ( no ZoomableImageView )

That two URLs got different results.

**Comment by finestructure** [comment]
Yes, it's two different issues, one of which I've fixed and the other will be fixed when we analyse 5.5 packages. 

The two different views expose the two different issues, hence the difference in which package is missing.

**Comment by rushairer** [comment]
It seems that something wrong when get the packagename of 5.5 package.

**Comment by finestructure** [comment]
Yes, it's because we're not using 5.5 yet to analyse the package.
