### ISSUE TITLE
Page rendering and missing data

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#126]
This is obviously something that's happening more for me since I have a partially analysed database (I normally only let `./analyze_loop.sh` run for 20-30 minutes usually after a reset) but there's something that concerns me a bit about how we're dealing with missing data when rendering the package page.

Sometimes, I click through from a search result to the package page and there's a piece of data needed to render that package page that results in the page being a JSON error response. It would make more sense to me if the page were able to render under *almost* any circumstance, with missing data rather than a total refusal to render. 

I know this is not going to happen in a live situation anywhere near as often, but I bet it will happen occasionally, and it's hard to test for. I can see two potential solutions for this:

1. We make the Package page much more tolerant about missing data. I'd much rather render an empty bullet (which isn't ideal!) than have the whole page fail.
2. We exclude any packages that will not render from the search results, meaning that it'd be much less likely that people would see a page in this state.

Oh, and regardless of which of these we go with, we should have some HTML formatted error pages rather than just outputting a JSON error. I've logged that separately as #125.

**Comment by finestructure** [comment]
Yes, that’s something we need to look at when refining `PackageShow.Model`. I’m starting to have to make fields optional here in order to be able to deal with missing data. The nice thing is the optionals really guide us and allow us to either fail late (on page rendering) or early, when querying.

We’re automatically benefitting from packages that tend to fail to render due to missing versions etc also not being picked up by the search query. But especially around other metadata like releases or commit info we’ll have to either transform the optional into placeholder text on the show page or collapse/hide the whole element.

BTW I have not yet encountered any JSON errors bubbling up (but I’m also not browsing that many packages). Would be good to know when/how that happens because I don’t think that _should_ actually be the case when it’s just missing data.
