### ISSUE TITLE
Support MacCatalyst Builds

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#1269]
I suspect this one might get shot down quickly, which is totally cool with me, but it could be nice to add a new build target for macOS via Catalyst.

My new [Swift Package](https://swiftpackageindex.com/Sherlouk/SpanGrid) supports iOS, but not macOS, and until I did a very simple patch a couple minutes ago didn't support Catalyst either. The SPI build matrix didn't highlight that fact, and perhaps it could have?

**Comment by daveverwer** [comment]
🔫 

😂

**Comment by Sherlouk** [comment]
Water pistol is really not that menacing 😂 Genuinely interested though is it truly off the cards?

**Comment by daveverwer** [comment]
> Water pistol is not that menacing 😂

That was intentional 👍

I can see a good argument for adding Catalyst as a platform and I do think it'd be worth adding as a separate platform rather than trying to aggregate the macOS compatibility into (native macOS OR macCatalyst) because they are so fundamentally different.

However, in terms of priorities, I can't say where it'd lie right now. It wouldn't be at the top of my current list, and given the fact that the implementation would lie inside the build system which isn't super easy to open-source given the close integration with our deployment environment, it would need to be primarily @finestructure who implements it.
