### ISSUE TITLE
Missing Package name valentinradu/Firestarter

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#1441]
I thought we fixed this, but we either didn't or this is a regression!

I went to add [Firestarter](https://swiftpackageindex.com/valentinradu/Firestarter) to the index tonight as it didn't show in search results only to find that it already existed in the `packages.json` file.

The package page is visible and everything looks good there, but the package is missing from search results:

- Search for [firestarter](https://swiftpackageindex.com/search?query=firestarter).
- Search for [valentinradu](https://swiftpackageindex.com/search?query=valentinradu).

The issue is that there's no package name on the `version` records, meaning the search view looks like this:

<img width="865" alt="Screenshot 2021-12-09 at 20 31 40@2x" src="https://user-images.githubusercontent.com/5180/145471286-39d556e2-155c-4165-9b72-64e0b103181d.png">

I think there are two issues here:

* The package name in the manifest is valid, and the JSON output from `dump-package` seems to be correct at a quick glance (see below).
* Packages that have no package name should still show up in search results. We should use the repository name if we don't have a package name like we do on the package page. Logged as #1442.

#### Package dump JSON

```json
{
  "cLanguageStandard" : null,
  "cxxLanguageStandard" : null,
  "dependencies" : [

  ],
  "name" : "Firestarter",
  "packageKind" : "root",
  "pkgConfig" : null,
  "platforms" : [
      ...
```

**Comment by chris-araman** [comment]
I'm not sure if this is related, but my packages don't appear in search, either, although they appear to have been indexed:
https://swiftpackageindex.com/chris-araman/AsyncCloudKit
https://swiftpackageindex.com/chris-araman/CombineCloudKit

Names appear for both in `swift package dump-package`  and `xcodebuild -list -json` as expected.

Tangentially but possibly related, the "Full Compatibility Report" links yield 404 errors:
https://swiftpackageindex.com/chris-araman/AsyncCloudKit/builds
https://swiftpackageindex.com/chris-araman/CombineCloudKit/builds
https://swiftpackageindex.com/valentinradu/Firestarter/builds

**Comment by finestructure** [comment]
Thanks for the additional into, @chris-araman ! I can see what the issue is: all these packages are referencing platform idioms like `macCatalyst` that we're not parsing yet:

```
dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "platforms", intValue: nil), _JSONKey(stringValue: "Index 3", intValue: 3), CodingKeys(stringValue: "platformName", intValue: nil)], debugDescription: "Cannot initialize Name from invalid String value maccatalyst", underlyingError: nil))
```

We'll need to figure out how to handle this. The options are

1. find the canonical source of inputs and extend the list
2. make parsing resilient and parse any new platforms into `.other(String)` or something
3. review if we're actually using `platform` for anything at all and can skip it entirely

I suspect 3. is an option, but it'll take some reviewing.

Option 2 would make us resilient vs changes in the manifest spec.

Option 1 is clearly the cleanest solution but it'll also mean that on every tools-version bump we'll need to remember to review the canonical list of platforms so we don't fail reading the manifest when it changes.

**Comment by finestructure** [comment]
I went with 1. Hopefully this won't change too often. The fix isn't hard, it's just that it's hard to find out that it's required. I can't see a way we'd find out that it's happening other than some monitoring on package dump failures.

Option 3 is probably undesirable because even though we don't use the field right now, it's something that could be relevant. (Although I think our build system captures a better version of it, so it might be redundant for our purposes in principle.)

**Comment by finestructure** [comment]
I've added a note to our "Add new Swift version" process description in infrastructure. That should take care of it.

**Comment by finestructure** [comment]
There are potentially 14 packages affected (via `select count(*) from versions where latest = 'default_branch' and package_name is null;`)

**Comment by daveverwer** [comment]
Thanks for tackling this @finestructure, and thanks for the additional information @chris-araman! I had this on my list of things to investigate but didn't get to it before the holidays. 

One thing that'll help with future expansions is fixing #1442 which will stop this problem from removing these packahes from search. I just added those build pages to that issue too.

**Comment by finestructure** [comment]
Package name for `valentinradu/Firestarter` is still `NULL` in staging despite deploying the platform fix. Package versions have been updated.

**Comment by finestructure** [comment]
Weird, `package_name` is correctly populated when I run analysis locally.

**Comment by finestructure** [comment]
Oh, of course. We're not re-analysing versions that don't have upstream changes. The fact that I'm explicitly analysing the package applies the change. We'll need to manually re-analyse the packages in question.

**Comment by finestructure** [comment]
I've manually re-analysed all packages with missing package names and Firestarter is now showing up in search on staging:

<img width="881" alt="CleanShot 2021-12-26 at 12 12 36@2x" src="https://user-images.githubusercontent.com/65520/147406263-a61ac369-6660-461e-8524-5e5f204a0c08.png">

I'll deploy and re-analyse affected versions in prod.

**Comment by finestructure** [comment]
Updated on prod as well. There are still some versions without package names but these are very likely due to different manifest errors, some of which we know about.

```
50181aee-4bb5-4c3a-b742-e52351867bda | https://github.com/apple/swift-distributed-actors/tree/main
3cd9ddf1-9254-4e67-8261-eed06f4a6802 | https://github.com/Azure/azure-sdk-for-ios/tree/main
1f8bda38-6490-4d3d-86c5-22262a89848a | https://github.com/palle-k/DL4S/tree/master
76c0b0a0-ff87-4ae9-a4be-4b9729ac4e0b | https://github.com/piemonte/Position/tree/main
7915b810-add1-4e68-ac68-44be9d959e64 | https://github.com/skywinder/web3swift/tree/develop
592e589b-f726-4a34-aeeb-5845b220437d | https://github.com/uber/ios-snapshot-test-case/tree/main
```

**Comment by chris-araman** [comment]
Thanks, @finestructure and @daveverwer!
