### ISSUE TITLE
Populate the "Recent Packages" and "Recent Releases" data

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#149]
- [x] create mat views for queries
- [ ] wire up queries in home page

The Recent Packages and Recent Releases lists on the home page need data.

## Recent Packages

This should be the last 10 (valid) packages ordered by created_at on the packages table. In other words, the last 10 packages that were added to the index.

## Recent Releases

The last 10 versions across all packages. Limited to be unique per package (so even if a package does two releases in quick succession, it's not listed twice).

**Comment by finestructure** [comment]
When counting releases, do we take any release or just stable releases?

**Comment by daveverwer** [comment]
I'd say any releases for this list.

The purpose of this list is people just browsing, maybe they'll see something interesting, so the quicker this data moves, the better in my opinion.

**Comment by finestructure** [comment]
I've got some query variants that are more or less complicated, depending on what we want to display.

The main issue is the package -> version 1:n relationship and the fact that we parse the package name from the version info and store it in the `versions` table.

That means that the simple "recent packages" query like the following doesn quite work out

```
-- recent packages (without name)
select p.id, p.url
from packages p
order by p.created_at desc
limit 10
```

because we don't have names. Of course we can join for those but at the cost of query performance:

```
-- recent packages
select p.id, v.package_name, max(p.created_at) from packages p
join versions v on v.package_id = p.id
where v.package_name is not null
group by p.id, v.package_name
order by max(p.created_at) desc
limit 10
```

`explain analyze` gives us a cost of 136 for the first and 3200 for the second, or in terms of exectuion time, 1.5ms vs 122ms. NB that this is before looking into applying any indexes. NB also that 122ms isn't terrible - but it is the homepage, so we should probably consider caching that somehow, perhaps with a materialzed view. This result is going to change very infrequently, so I think that'd be a good use.

For "recent releases", we can query directly on the `versions` table alone without a join

```
-- recent releases
select package_id, package_name, max(commit_date)
from versions
where
commit_date is not null
and package_name is not null
and reference->>'tag' is not null
group by package_id, package_name
order by max(commit_date) desc
limit 10
```

provided we don't need the package url. I don't think we do, looking a the current design - or at least I assume that we link to our package page via the package id and not the original package, right?

The cost for the "recent releases" query is 2640 or 112ms. Again, no indexes applied yet.

Also not terrible but we'll probably want to do better given those two queries would both run on each hit on the homepage.

**Comment by finestructure** [comment]
I'll check what indexes and views will do to those query costs.

**Comment by daveverwer** [comment]
> provided we don't need the package url. I don't think we do

We don't

> I assume that we link to our package page via the package id and not the original package, right?

Correct.

**Comment by finestructure** [comment]
Sweet, materialized views bring this down to 0.02ms each :) The only slight downside is that we need to scheduled a call to refresh them - but there are natural places to do that in the Reconciler and Analyzer.

**Comment by daveverwer** [comment]
> Sweet, materialized views bring this down to 0.02ms each :)

Good enough 😂
