### ISSUE TITLE
Package disappeared from Index (malformed package file)

### ISSUE THREAD

**Issue by calimarkus** [SwiftPackageIndex/SwiftPackageIndex-Server#1853]
I updated my package file with a typo. As a result `swift package dump-package` failed.
The index didn't handle this very well. My package still showed up in search results, but upon opening it, it just said "This package is not on the index yet". I'd expect it to display the last working/correct version instead? Also I couldn't find any "build results" or error messages for the package.

**Explain the steps needed to reproduce the bug**

Push a broken Swift Package file to the repo of an already listed package.

**What was the expected behaviour?**

See the last working version on the index website. And/or maybe some error description for the current version?

**Comment by daveverwer** [comment]
While I agree it would be nice if we could find some way to feedback errors to package authors, I don’t think that showing the old version of a package or displaying the underlying error to users is the right approach.

The biggest problem we have with feeding back issues to package authors is that we don’t know who the authors are. We may add user accounts one day, which would be one way for us to know (although it’s more challenging than it seems as many packages have several authors), but without that, I don’t think we can do it.

With the package page showing old data, I don’t really like that idea. The primary purpose of the package index is to show people packages they can use. It would be tough to convey that while a package may have been what they are looking for at a specific version, the current version cannot be used as a package at all. If a package is broken to the point that `dump-package` doesn’t run, I think we’re correct to remove it from the index.

That may seem harsh for packages with a temporary problem, like in this case, but what about packages that break and stay broken for long periods? Our site needs to cope with both situations.

I feel that solving this problem is outside the scope of what we’re trying to do right now. While some of what we do does look like a CI system, we’re not trying to _be_ a CI system yet.

I’d suggest a better way to stop this type of error today would be to add some CI to your package’s repository. That way, you’ll get notified if something breaks and when fixed, the package index will pick up a working version when it's pushed.

I think I’ll close this bug, but thank you so much for the suggestion and feedback!
