### ISSUE TITLE
Lighter docs not showing up

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1977]
Reported by @helje5 via DM.

There are not docs in the bucket. The [build for 1.0.2](https://swiftpackageindex.com/builds/C6183D47-282A-43B5-971A-B3170A81934F) shows

```
[builder] Build complete! (14.79s)
[builder] Build complete.
[builder] ========================================
[builder] GenerateDocs
[builder] ========================================
[builder] Done.
```

which looks suspicious.

**Comment by finestructure** [comment]
Hold on, 1.0.2 had no `.spi.yml` yet, so this is not suspect.

**Comment by helje5** [comment]
Ah, OK, I thought it does the gen on the main branch (`develop` in my case).

**Comment by finestructure** [comment]
It will, just not immediately. It can take up to 24h, depending on repo-activity. I'll double check which ref was built and/or poke it to make sure it works ok.

**Comment by finestructure** [comment]
Yeah, we're currently tracking `6c00e5005d709f94113d67949784e5c1138a0877` which isn't the latest due to 24h coalescing. We only build tags immediately, and coalesce default branch builds over 24h.

**Comment by finestructure** [comment]
Ok, there's definitely something wrong here:

```
error: Unknown subcommand or plugin name 'generate-documention'
```

The problem is `Package@swift-5.swift`, which seems to override `Package.swift`. We're append the docc plugin to `Package.swift` but the builder actually picks up `Package@swift-5.swift` when building the package with Swift 5.6.

**Comment by finestructure** [comment]
I'm not sure if there's a way to let SPM tell us which manifest it's going to use. Unless there is, the only way I can see us working around this is attach the plugin dependency to _all_ `Package.swift` + `Package@*.swift` files.

**Comment by finestructure** [comment]
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/137 by appending the plugin to all manifests. It's ugly but so is the whole manifest hackery...

**Comment by helje5** [comment]
I know that the setup is a little weird, but actually necessary to get things run (mostly) properly in Xcode.
- the main `Package.swift` *must* be 5.6 for Xcode, otherwise it doesn't detect plugins (i.e. 5.7 does NOT work)
- the `Package@swift-5.7.swift` is also required to get things to actually work in Xcode :-)
- the `Package@swift-5.swift` is required when building just the `Lighter` library (w/o the plugins, which require 5.6+). That's an important use case.

SPM picks up the most recent version that matches, e.g. if you have 5.7, it'll use the right `Package@swift-5.7.swift`. If you are building for DocC it should never pickup `Package@swift-5.swift`.
I think what is happening is that your builder runs on 5.7 and picks up the `Package@swift-5.7.swift`, not the `5.swift`.
In fact, you probably shouldn't add the docc plugin to manifest that are lower than v5.6.

**Comment by finestructure** [comment]
Deployed and fixed :)

https://swiftpackageindex.com/Lighter-swift/Lighter/develop/documentation/lighter
