### ISSUE TITLE
Image links are broken in hosted documentation

### ISSUE THREAD

**Issue by jbadger3** [SwiftPackageIndex/SwiftPackageIndex-Server#1983]
**Please describe the bug**
Images in documentation hosted on SPI do not appear to be working.  (perhaps this is a feature that needs implementation?)

**Explain the steps needed to reproduce the bug**
I haven't done an extensive search, but my package [Terminus](https://swiftpackageindex.com/jbadger3/Terminus) doesn't have images as you can see [here](https://swiftpackageindex.com/jbadger3/terminus/main/documentation/terminus/getting-started), and SwiftParse seems to be [missing images](https://swiftpackageindex.com/parse-community/Parse-Swift/main/documentation/parseswift) as well.

**What was the expected behaviour?**
Images rendered/supplied in online docs.

**Screenshots**
![SPI_Image_Bug](https://user-images.githubusercontent.com/22161798/185665562-3892658f-4e86-44dd-bfb2-d75f54c78bec.jpg)

**What web browser were you using? (if relevant)**

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop
- Browser Tried both Safari and FireFox

**Additional context**

Sorry if this is well known.  I didn't see any open issues related to the topic.

**Comment by finestructure** [comment]
Thanks for reporting this, @jbadger3! That's definitely a regression, because I also see this in Stream's EffectLibrary which I know _was_ working previously. This is probably due to some changes I made recently.

<img width="738" alt="CleanShot 2022-08-20 at 14 52 05@2x" src="https://user-images.githubusercontent.com/65520/185747070-e33bf5f4-cdca-406e-9747-b1def1c7f204.png">

**Comment by finestructure** [comment]
Fix will be deployed shortly.

**Comment by jbadger3** [comment]
Excellent!  @finestructure happy to help out.
