### ISSUE TITLE
Not Showing Documentation link on page for STKAudioKit

### ISSUE THREAD

**Issue by aure** [SwiftPackageIndex/SwiftPackageIndex-Server#1992]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/AudioKit/STKAudioKit

**Please explain what data is incorrect and what you expected to see**

I expected to see a Docc documentation link on the side bar.

I have included .spi.yml and the package builds on 5.6 (using Xcode, not SPM).

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

Please find the builds exhibiting the problem from the "Full Package Compatibility Report" menu item in the side menu and link the build reports here.

https://swiftpackageindex.com/builds/D7F23AF5-1037-4B2A-8EC6-AA90BDCCABE8

Thanks for your attention. This is one of many repos I have that I would like to have documentation generated for so I'd like to get the kinks out sooner rather than later.

**Comment by daveverwer** [comment]
Thanks for raising this, Aurelius and apologies for the problems.

The issue in this case is that if the platform configuration is omitted, we will run the documentation build process through the `swift build` command on macOS rather than by using `xcodebuild`. Unfortunately, with this package [the `swift build` configuration fails](https://swiftpackageindex.com/builds/BDD1F73E-EDA5-4AE2-8A0E-26D2479220AD), and so stops documentation building.

I have just opened a PR on your repo to switch that to use `xcodebuild`. Once that PR is merged, it will take several hours for it to attempt another build as we limit default branch builds to one per 24-hour period, but it will generate the docs at that point.

We are working on two features that will make this kind of issue easier for package authors to identify. First, we are working on some documentation for the `.spi.yml` file in #864, and secondly, we will identify the build where documentation is generated on the build matrix through #1887 and #1888.

**Comment by daveverwer** [comment]
I'll leave this open until we have verified the documentation is generated.

**Comment by aure** [comment]
We are also hosting documentation on our web site and having issues with setting the hosting base path when not using the swift build system, it seems like you that figured out, may I ask how you accomplish that within the xcodebuild doc building environment?

**Comment by finestructure** [comment]
I’ve described our process [on the Swift forums](https://forums.swift.org/t/swift-docc-sidebar/55250/28) and that is still how we do it. In a nutshell, via `xcodebuild`:

```bash

xcodebuild \
-derivedDataPath "$PWD/.derivedData" \
docbuild \
-scheme "\(target)" \
-destination 'generic/platform=\(platform.rawValue)'

xcrun docc process-archive transform-for-static-hosting \
$(find "$PWD/.derivedData" -type d -name "*.doccarchive") \
--output-path "\(outputPath)" \
--hosting-base-path "\(hostingBasePath)"
```

**Comment by aure** [comment]
Thanks Sven and Dave, you guys are truly amazing.

**Comment by daveverwer** [comment]
I came to check in that this was now resolved and it looks like we do have a problem. 

From [the build log](https://swiftpackageindex.com/builds/D8D4F91A-A247-4418-BF68-116FD8CCF7C6):

```
========================================
GenerateDocs
========================================
Generating docs at path:  spi-builder-workspace/.docs/audiokit/stkaudiokit/main
Repository:               AudioKit/STKAudioKit
Target:                   STKAudioKit
Error while generating docs: infrastructureError("generating documentation not yet support on \'macosXcodebuild\'")
Done.
```

**Comment by finestructure** [comment]
Ah yes,  we only support doc builds on `macos-spm` or `ios` for the moment. If I recall correctly there were issues building docs with Xcode on platforms other than iOS.

I see that your package fails to build with SPM / Swift 5.6 on macOS but does pass with Swift 5.5. Presumably that's something that's fixable?

**Comment by aure** [comment]
I didn't want to disrupt your test but we did in fact change the code so that it could be built the normal way. Right now it is on branch, does the spi.yml spec allow for using a specific branch for the documentation generation?  I'd love to know the answer so please post here, but I will close the issue as it resolved.

**Comment by finestructure** [comment]
We don't, no. Just the default branch and tags.

**Comment by aure** [comment]
Good to know thanks!
