### ISSUE TITLE
package page is showing two of the same version, not latest release version and main branch

### ISSUE THREAD

**Issue by heckj** [SwiftPackageIndex/SwiftPackageIndex-Server#2002]
I noticed the hosted documentation, which had worked previously (but only for the `main` branch) was missing.
Then when I looked at the package page, I noticed something odd: the same version is listed twice - as opposed to the release version and the `main` branch - which I think was there previously.

**Explain the steps needed to reproduce the bug**

1. Navigate to to https://swiftpackageindex.com/heckj/CRDT

I'll attach a screenshot when I figure out how to navigate through the *&%*&$*&$^ iPad interface...

**Comment by heckj** [comment]
![IMG_0168](https://user-images.githubusercontent.com/43388/187841482-6dd75873-9425-465a-b02f-2fd760267a56.png)

**Comment by finestructure** [comment]
So this was at least in part caused by a Linux build backlog (which has now cleared) that prevented the default branch build of your package to be processed. Now that that's caught up, the doc link is working again. It's only showing `main` though.

The [0.5.0-apha1 build has been processed](https://swiftpackageindex.com/builds/A0B7A842-B348-491A-9ABE-7CC466ABE3F1) and it should be available - but it's missing.

**Comment by heckj** [comment]
the 0.5.0 build won't have the docs, that was due to my using the main branch on the docc-plugin when I was setting that up, but it'll be corrected in my next release. Thanks @finestructure, glad that was a temp glitch and not a processing bug.

**Comment by finestructure** [comment]
> the 0.5.0 build won't have the docs, that was due to my using the main branch on the docc-plugin when I was setting that up

Ah I see, thanks for clearing that up!
