### ISSUE TITLE
No documentation generated even after specifying `documentation_targets`

### ISSUE THREAD

**Issue by soumyamahunt** [SwiftPackageIndex/SwiftPackageIndex-Server#2209]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/SwiftyLab/AsyncObjects
- https://swiftpackageindex.com/SwiftyLab/ValidatableKit
- https://swiftpackageindex.com/SwiftyLab/SwiftAnalyticsKit

**Please explain what data is incorrect and what you expected to see**

All of the above packages have specified `documentation_targets` but missing documentation section in the site.

**Additional context**

Please find the manifest files for the packages:

https://github.com/SwiftyLab/AsyncObjects/blob/main/.spi.yml
https://github.com/SwiftyLab/ValidatableKit/blob/main/.spi.yml
https://github.com/SwiftyLab/SwiftAnalyticsKit/blob/main/.spi.yml

**Comment by finestructure** [comment]
Hi @soumyamahunt, thanks for raising this issue.

In order to generate docs, (currently) the package manifest needs to include the docc-plugin. We add it to the dependencies if it doesn't exist so authors don't need to add the dependency themselves in their package.

It turns out that in your case, our heuristic to detect the plugin dependency [is failing](https://swiftpackageindex.com/builds/CC264C3B-2977-4157-93EE-F6E73D647FA5):

```
========================================
GenerateDocs
========================================
Generating docs at path:  spi-builder-workspace/.docs/swiftylab/asyncobjects/main
Repository:               SwiftyLab/AsyncObjects
Swift version used:       5.7
Target:                   AsyncObjects
error: 'spi-builder-workspace': duplicate dependency 'swift-docc-plugin'
Error while generating docs: ShellOut encountered an error
Status code: 1
```

That's because we're looking for the string `https://github.com/apple/swift-docc-plugin`, whereas your manifests have:

```swift
        .package(url: "\(appleGitHub)/swift-docc-plugin", from: "1.0.0"),
```

I can think of a couple of simple ways of dealing with this:

- you could drop the plugin entirely since we don't need it - and maybe you don't either?
- you could avoid using string interpolation for the plugin
- we could loosen our match by just looking for `/swift-docc-plugin`

Would one of the first two options work for you?

**Comment by soumyamahunt** [comment]
Thanks for the quick response @finestructure, I have removed the string interpolation from the package dependency declaration. Do I have to update the tag as well for the documentation generation to work?

As a long term solution I think pattern matching should be done on the output of `swift package dump-pack
age` instead of directly on `Package.swift` manifest.

**Comment by finestructure** [comment]
> Do I have to update the tag as well for the documentation generation to work?

No, I've re triggered the builds in question to confirm the docs are being generated and they're all up now:

<img width="732" alt="CleanShot 2023-01-08 at 09 17 03@2x" src="https://user-images.githubusercontent.com/65520/211186806-aa175ad6-1e84-41fb-8ecb-57f1b829ef5b.png">
<img width="727" alt="CleanShot 2023-01-08 at 09 17 11@2x" src="https://user-images.githubusercontent.com/65520/211186811-8831f600-b741-4735-b88a-ca18e1ea8afb.png">
<img width="734" alt="CleanShot 2023-01-08 at 09 17 20@2x" src="https://user-images.githubusercontent.com/65520/211186815-e5b0faa4-8596-43da-b69b-edc856434ac6.png">

I'll go ahead and close this issue now. Please reopen it if you're still having issues!
