### ISSUE TITLE
swift-markdown 0.2.0 documentation is missing

### ISSUE THREAD

**Issue by Kyle-Ye** [SwiftPackageIndex/SwiftPackageIndex-Server#2490]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/apple/swift-markdown/

**Please explain what data is incorrect and what you expected to see**

The latest version of swift-markdown is 0.2.0. But the documentation only show `main` and `0.1.0`

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

Please find the builds exhibiting the problem from the "Full Package Compatibility Report" menu item in the side menu and link the build reports here.

- https://swiftpackageindex.com/builds/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
- https://swiftpackageindex.com/builds/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY

Where possible, try and replicate the problem you have found by running the "Build Command" at the top of a build report. This command is what our build servers execute.

**Screenshots**

If they would be helpful, please add screenshots to help explain the problem.

**Additional context**

Is there anything else we might find useful?

**Comment by finestructure** [comment]
Thanks for the report, @Kyle-Ye ! The problem is that swift-markdown 0.2.0 [has no `.spi.yml` file](https://github.com/apple/swift-markdown/tree/0.2.0). We initially built in special handling for swift-markdown, which is how 0.1.0 got built.

Since then, a `.spi.yml` file has been added to `main` (~ 6 months ago) but that seems to have been excluded from the 0.2.0 release somehow (which seems to have happened ~2 months ago).

I'm not sure how that happened but I think as soon as there's a new release this should be rectified.

**Comment by finestructure** [comment]
Pinging @QuietMisdreavus who released 0.2.0 and might have some insight how it ended up without `.spi.yml`!

**Comment by Kyle-Ye** [comment]
Some related PR https://github.com/apple/swift-markdown/pull/137

**Comment by QuietMisdreavus** [comment]
Swift-Markdown's `0.2.0` release was tagged off its `release/5.8` branch, since that was the last commit that was officially "released" (as part of Swift-DocC in the Swift 5.8 release). When Swift 5.9 hits a final release, i can tag a new release based on the `release/5.9` branch, [which does have an `.spi.yml` file](https://github.com/apple/swift-markdown/tree/release/5.9).

**Comment by finestructure** [comment]
Ah right, I was wondering if it’s something like that after I posted. Thanks, @QuietMisdreavus !
