### ISSUE TITLE
LLVM-15+ dependency needed

### ISSUE THREAD

**Issue by dabrahams** [SwiftPackageIndex/SwiftPackageIndex-Server#2545]
I guess this should've been an issue all along (Discussed in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/2544)

<div type='discussions-op-text'>

<sup>Originally posted by **dabrahams** August  9, 2023</sup>
Per [this section](https://swiftpackageindex.com/swiftpackageindex/spimanifest/1.0.0/documentation/spimanifest/commonusecases#Images-for-Linux), I'm opening an issue for the addition of LLVM-15 as a dependency to your Linux build image.

I'm not sure if that's really the right answer; if we should be adding something to our SPI manifest instead, please let us know.  Note that our setup [requires](https://github.com/val-lang/val#prerequisites) the generation of a pkgconfig file for LLVM.  Or perhaps we should be using our own devcontainer.  Please let us know!

/cc @kyouko-taiga

Local testing yields:

```
docker run --rm -v "$PWD":/host -w /host registry.gitlab.com/finestructure/spi-images:basic-5.8-latest swift build
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
warning: couldn't find pc file for llvm
[0/1] Planning build
[1/1] Compiling plugin Format Source Code
[2/2] Compiling plugin GenerateManual
[3/3] Compiling plugin Lint Source Code
[4/4] Compiling plugin TestGeneratorPlugin
[5/5] Compiling plugin ValidatorPlugin
Building for debugging...
/host/.build/checkouts/Swifty-LLVM/Sources/llvmshims/src/shim.cc:1:10: fatal error: 'llvm-c/TargetMachine.h' file not found
#include "llvm-c/TargetMachine.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[5/25] Compiling shim.cc
```
</div>

**Comment by finestructure** [comment]
The PR referenced above should fix the Linux build and generate docs. I'll retrigger builds manually once it's merged to confirm it's working, so we don't have to wait for the 24h change coalescing.

**Comment by dabrahams** [comment]
Thanks @finestructure!  I'll see what I can do with this.

**Comment by dabrahams** [comment]
Merged; let's see if we get some docs!

**Comment by finestructure** [comment]
Well, we've got a partial success - the build:

![CleanShot 2023-08-15 at 07 29 27@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/d8a84088-761d-4bf2-bfa9-2f9c66eea53b)

What I didn't realise is that we're not using the custom base image for the doc build - which of course fails just like it did before. That should be fixable.

**Comment by dabrahams** [comment]
And why does it only succeed with 5.9?

**Comment by finestructure** [comment]
Ah sorry, I'd only manually triggered 5.9 while I was sorting out the doc builds. We coalesce all default branch changes over 24h, that's why these didn't get kicked off yet. I've manually triggered them now for the other Swift versions on Linux.

The doc build is also working now, although the result is perhaps not what you expect. The CLI target (which is the default we show, the first in the list) does not have any symbols:

![CleanShot 2023-08-15 at 15 53 13@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/16206d9b-5d06-415f-a79e-36220dcc7b4b)

I don't see any doc gen errors, so perhaps this is as it should be. Perhaps the `Core` target would be better to sort first.

**Comment by finestructure** [comment]
I'll go ahead and close this now, please reopen if you're still seeing issues.
