### ISSUE TITLE
Documentation did not build

### ISSUE THREAD

**Issue by stephencelis** [SwiftPackageIndex/SwiftPackageIndex-Server#2630]
Sorry for so many issues lately! Let me know if you prefer a discussion or something else to look into these questions.

**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/pointfreeco/swift-macro-testing
- ...

**Please explain what data is incorrect and what you expected to see**

I have an .spi.yml here specifying a documentation target: https://github.com/pointfreeco/swift-macro-testing/blob/main/.spi.yml

However, no documentation seemed to generate. Am I missing a configuration option?

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

I don't think documentation builds are included in the build list...

Relatedly, I am seeing some timeouts on SPI that I'm not able to reproduce locally:

https://swiftpackageindex.com/pointfreeco/swift-macro-testing/builds

Any idea what happened?

**Comment by finestructure** [comment]
Hi @stephencelis , no problem at all! It's good to see the docs being actively used and we're happy to hear about issues so we can address them :)

I've opened a PR with a fix. The problem is that we still build docs with 5.8 for now (we always use the latest stable release and haven't updated to 5.9 just yet). Since the package is 5.9+ there's no valid build to generate the docs with.

I've changed your `.spi.yml` to opt into building the docs with 5.9 - or you can wait until we've updated to 5.9, which should happen very soon now.

If you merge that change, it's probably best to remove the `swift_version` opt-in once we've moved to 5.9. This will ensure that the package gets built with the latest release version of Swift in the future.

**Comment by stephencelis** [comment]
Thanks!

**Comment by stephencelis** [comment]
@finestructure Any way to kick off a rebuild for `main`, or should it automatically pick up some time soon?

**Comment by finestructure** [comment]
It should pick up soon but the bigger problem is a build backlog we've accrued over the last few days due to some hardware issues.

I'll have a look how things are going in the morning and will give it a poke!

**Comment by finestructure** [comment]
I triggered it manually to get it past the backlog, here you go :)

https://swiftpackageindex.com/pointfreeco/swift-macro-testing/main/documentation/macrotesting
