### ISSUE TITLE
Search results don't show link to self-hosted docs

### ISSUE THREAD

**Issue by 0xTim** [SwiftPackageIndex/SwiftPackageIndex-Server#2702]
**Please describe the bug**

When searching for packages, packages that self-host their documentation don't appear to show a "Has Documentation" icon in the search results.

**Explain the steps needed to reproduce the bug**

1. Navigate to [search that returns a Vapor package](https://swiftpackageindex.com/search?query=swift)
2. Vapor does not show "Has Documentation" on the search page, clicking through to the page shows the documentation link

**What was the expected behaviour?**

Vapor result should show "Has Documentation"

**Screenshots**

<img width="618" alt="Screenshot 2023-11-07 at 20 10 44" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/9938337/a1688985-28ef-4929-a2fe-3183d99e1cd2">

**Additional context**

Haven't tested with other self-hosted packages outside of Vapor as I don't know any of the top of my head

**Comment by heckj** [comment]
I checked Automerge (also externally hosted docs), and it also doesn't show as having docs in the search results, although there's a documentation page link on the SPI page for the project. 

![image](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/43388/52869d3a-0b4b-4b25-b88c-07a7100811ac)

**Comment by heckj** [comment]
Suspecting this was a regression that might be easy to spot, I went poking through the code to resolve it. 

## my debugging digging and code archeology

The information for if a package has docs (or not) is sourced from a database query, without any amendment elsewhere in the pipeline before it's displayed in the search results. (`App/Core/Search.swift' in the `query()` function). 

The has_docs result was added into the DB migrations starting with migration 55 through 66 (version 11 of the search query) - none of the migrations since have effected it. The queries consistently look for `ARRAY_LENGTH(doc_archives, 1) >= 1 AS has_docs` in the query.

Doc archives shows up around migration number 52, which is stashing a list of JSON files as its results.

The only place I spotted anything related to the manifest (where I think anything external would be sourced) is in migration 49, where the manifest (as a JSON file) is added as a field `spi_manifest` to the versions schema.

I'm guessing the background processing of the builder is where doc_archives is getting updated - and where any updates to the manifest files would be processed, which I suspect is the place where this would likely best be fixed. I've not yet found what appends JSON "blob" values to the table `Versions`, field: `doc_archives`

For the package pages, the function `canonicalDocumentationTarget` is used to provide a canonical version/link to the documentation, checking the Versions schema for an external link (`spiManifest.externalLinks?.documentation`) as an explicit override. I'm not seeing anything of the same in the search queries - so I'm not sure if the intention is to stash an external link in the database as `Versions.doc_archives` so that it shows up in the queries as having some documentation, or if the materialized search view should be updated to account for any doc archives the build systems creates as well as checking for if there's an `externalLink.documentation` as that boolean marker.

## take-away to fix

If this is a regression, I can't spot where it was working previously, or how - at least from the current code. I was doodling through all this to potential submit a PR to "fix it", but at this point I suspect I'd need a little @daveverwer and @finestructure  guidance for how they'd like the process to ideally work, and I'm happy to put some time into making that happen.

**Comment by finestructure** [comment]
Apologies @0xTim , I missed this when you posted the issue :( And thanks @heckj for the poke :) I'll take a look at this now.
