### ISSUE TITLE
Render :shortcode: emojis in Package summaries

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#276]
<img width="741" alt="Screenshot 2020-06-05 at 11 57 04" src="https://user-images.githubusercontent.com/65520/83863592-d0620480-a723-11ea-96bf-a00b0352649f.png">

**Comment by daveverwer** [comment]
I had this on the list for the SwiftPM Library, there's a publicly available list of these somewhere. I thought GitHub had a publicly available list, but I can't find it now.

Slight problem is that there's no real standard for the words to refer to the emoji apart from the very long "official" names like "face with smiling eyes", but that's not what these are.

https://github.com/muan/emojilib seems promising, if we can't find the GitHub one.

**Comment by Sherlouk** [comment]
I can't remember exactly where we sourced it but on GitHawk we have this master list:

https://github.com/GitHawkApp/GitHawk/blob/master/Resources/emoji.json

This includes the GitHub special emojis like :shipit: :trollface: etc which are not part of the standard emoji set.

**Comment by Sherlouk** [comment]
So it turns out if I review my own commit on the file above, the original and official source is [github/gemoji](https://github.com/github/gemoji).

However, about a year ago under [040aebe](https://github.com/github/gemoji/commit/040aebef6445fc37df9e12590aa3ffed7ed3b49e) they removed all of the GitHub custom emojis from the master document used by GitHub. The latest raw JSON (with only unicode emojis) can be found here: https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json

In the pull request relating to the above change [#158](https://github.com/github/gemoji/pull/158) they mention that the custom ones are mostly unused and they plan to get rid of them with the exception of `:octocat:` and `:shipit:` but they haven't yet removed them.

The custom images can all be downloaded from [here](https://github.com/github/gemoji/tree/4b2d44d272c2b3224e91d7ce873a9bda0946add3/images).

So a decision needs to be made:
1. include all custom emojis
2. include the two custom emojis expected to remain :octocat: :shipit: 
3. include none of the custom emojis

**Comment by daveverwer** [comment]
I'd say we shouldn't support the custom emojis.

I just did a search through all summaries in the live database and neither of the two that are expected to remain is in use right now. The fallback of just seeing the shortcode is also fine if they ever do get used 👍

I'd love to see this get completed if you're up for it @Sherlouk.

**Comment by Sherlouk** [comment]
I think it 100% makes sense to just tackle standard unicode emojis for now - though my gut is saying we shouldn't discount custom emojis just yet as when we do the work for including README's into the package listing we may discover more emojis are used there... Can always tackle that separately though!

More than happy to own this 👍

**Comment by daveverwer** [comment]
> Can always tackle that separately though!

Yep, let's do that as a separate issue if we feel it's necessary when we get to READMEs. Which I'd like to prioritise soon as that is one of the most important pieces of information people use to judge a package.
