### ISSUE TITLE
Inaccurate Scores

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#2764]
So I'm taking a look at [this package](https://swiftpackageindex.com/CuriositySoftware/swift-property-name/information-for-package-maintainers) (randomly chosen) and the new Score matrix (awesome work btw!)

<img width="852" alt="Screenshot 2023-12-04 at 12 30 01 pm" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/15193942/eaa8c7aa-4b9e-4ca2-9d67-9914d1fb3570">

It cites that this package has a score of 65. Though I'm unsure of the accuracy of this.

Looking at [the package itself](https://swiftpackageindex.com/CuriositySoftware/swift-property-name) SwiftPackageIndex states:

"This package depends on 1 other package.", and yet the score matrix says it "Has no dependencies.". It also says that having no dependencies = a score of 0, though the [Score.swift](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/main/Sources/App/Core/Score.swift#L93) suggests that a project with less than 3 dependencies should get a score bonus of 5.

The score matrix also says it has no contributors, but the main page says it was written by two people. That's not really clear.

<img width="895" alt="Screenshot 2023-12-04 at 12 33 43 pm" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/15193942/a43e48e4-2265-452d-8417-11f5fb439ddb">

I'm not sure if its the matrix, the score calculation, or something else which is broken - but this data doesn't add up.

**Comment by finestructure** [comment]
Thanks for the report, @Sherlouk ! I'm taking a closer look.

**Comment by finestructure** [comment]
I've re-analysed this package locally and it updated the score from 65 to 70 (via the dependency score → 5). The breakdown now also shows two contributors.

I can explain why the dependency score was off at first. This is a newly added package and we get dependency information from the build step. However, on the first pass of determining the score, the builds wouldn't have reported back in yet, so that's why the score is 0 until analysis updates the package again.

NB: This would also be the case when there's a new default branch version. We may want to trigger an out-of-cycle score update to shorten the gap until analysis comes around again. Alternatively, we could perhaps base dependency information off of release branches (if present). That would make the figure more stable and require fewer updates, and places where they're triggered from. That would need some care and thought.

What's odd is that the author count was off as well. That's something that's entirely determined within analysis and should be stable immediately.

I've spot checked other packages and didn't see any with author discrepancies. Did you have an further examples for those, James?

**Comment by finestructure** [comment]
> Hold on, I missed the very first commit is also yimajo, albeit with a different avatar. I'll need to check what the underlying author refs actually are.

Ok, I can reproduce this locally. I've deleted the `swift-property-name` package, then ran

- reconcile
- ingest
- analyse

This correctly shows two authors on the package page but 0 contributors in the score breakdown. After running `analysis` one more time, the contributor breakdown is correct.

I wonder if this is due to the first analysis pass doing a `clone` vs subsequent ones doing a `fetch` or something like that.
