### ISSUE TITLE
Index not showing latest versions for lottie-ios and lottie-spm packages

### ISSUE THREAD

**Issue by calda** [SwiftPackageIndex/SwiftPackageIndex-Server#2875]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/airbnb/lottie-ios
- https://swiftpackageindex.com/airbnb/lottie-spm

**Please explain what data is incorrect and what you expected to see**

We released 4.4.0 of both of these packages last week, but the index is showing info for outdated versions:
 - lottie-ios incorrectly shows 4.2.0 as the latest version
 - lottie-spm incorrectly shows 4.3.4 as the latest version

There have been several releases since 4.2.0 (nine months old). The index also says the master branch was last modified 4 months ago, even though we have very regular activity in the repo.

I expect both pages to list 4.4.0 as the latest version.

Is this an issue with how the repo or package is configured on our end?

**Comment by finestructure** [comment]
Thanks for the report @calda , I'll take a look!

**Comment by finestructure** [comment]
Ok, this is a very interesting problem which may take some fiddling to fix for the existing versions. The problem is your `platform` declaration

```
.custom("visionOS", versionString: "1.0")
```

which we fail to parse. I believe you're using the `custom` field, because your manifest has the tools-version 5.7 and you can only use

```
.visionOS("1.0")
```

from 5.9 onwards. Now the problem is that we're using too strict an interpretation of `SupportedPlatforms` [as defined in SwiftPM](https://github.com/apple/swift-package-manager/blob/main/Sources/PackageDescription/SupportedPlatforms.swift), which would require

```
.custom("visionos", versionString: "1.0")
```

(Note the lowercase "os".) It seems like SwiftPM actually accepts both spellings while we're using an enum with all lowercase keys. As I said, I believe we're being too strict here.

Now the problem is that you can't even fix this for the old versions, only going forward. We'll need to update our manifest parsing to be case-insensitive, which should be feasible.

**Comment by finestructure** [comment]
Just to clarify, the canonical version seems to be

```JSON
    {
      "options" : [

      ],
      "platformName" : "visionos",
      "version" : "1.0"
    }
```

from `swift package dump-package` which is what you get when you use `.visionOS("1.0")` for tools-version 5.9.

I can't tell but I assume (because you'd probably have had problems otherwise) that SwiftPM also accepts `visionOS` here if you use a `custom` field with a capitalised `OS` spelling.

**Comment by calda** [comment]
Nice find!

Yeah, the current implementation in our `Package.swift` is supported as far as I can tell, since our package works properly on visionOS.

**Comment by finestructure** [comment]
I've re-analysed the two packages and they're now showing the latest versions again 🚀

**Comment by calda** [comment]
Thank you!
