### ISSUE TITLE
visionOS Build is succeeding but I know it is broken

### ISSUE THREAD

**Issue by mattmassicotte** [SwiftPackageIndex/SwiftPackageIndex-Server#2923]
**Please describe the bug**

The visionOS build for the package [TextFormation](https://swiftpackageindex.com/ChimeHQ/TextFormation) is broken, but it is building successfully on SPI.

**Explain the steps needed to reproduce the bug**

I'm pretty sure this has something to do with the xcodebuild invocation. Building with in the Xcode UI for both simulator and device fails. But I've tried a variety of configurations with `xcodebuild` from the command line and they all seem to be working for some reason.

**What was the expected behaviour?**

This should definitely not be building successfully.

**Additional context**

I honestly do not understand what's going on, but I cannot make this fail from the command line myself.

**Comment by mattmassicotte** [comment]
Yup that's it. I had copy-pasta'ed the scheme name. This command fails for me locally:

```
xcodebuild build -scheme TextFormation -destination generic/platform=visionOS
```

**Comment by finestructure** [comment]
Huh, that's bizarre. We shouldn't be picking that scheme, I'll need to check what's going on with our scheme heuristics.

Thanks for the report, @mattmassicotte !

**Comment by finestructure** [comment]
So I know what's happening but I don't know exactly why and how to best address it.

Your package lists four schemes when you run `xcodebuild -list -json`:

```json
{
  "workspace" : {
    "name" : "TextFormation",
    "schemes" : [
      "TextFormation",
      "TextStory",
      "TextStory-Package",
      "TextStoryTesting"
    ]
  }
}
```

This is the input to our package scheme detection heuristics. One of them is to filter for `*-Package` schemes and if there's only one, that's the one we pick. That's clearly wrong in this case, so the first impulse is to reject this heuristic.

If we do that, we probably fail to build some (many?) packages. We could recover some if we only pick `*-Package` if it's the only scheme.

Looking at the JSON one might think to check if there's a scheme with the same name as the workspace name. The problem with that is that the workspace name is really the checkout directory base name. We check out all repositories into `<tempdir>/checkout` and when you run `xcodebuild -list -json` on that you get

```json
{
  "workspace" : {
    "name" : "checkout",
    "schemes" : [
      "TextFormation",
      "TextStory",
      "TextStory-Package",
      "TextStoryTesting"
    ]
  }
}
```

😖

Of course, we could look at the project URL's last path element ... and we'd be placing another piece on our jenga tower of scheme guesses.

I wanted to get a feel how broken our assumption is that picking the autogenerated `*-Package` is a good idea. As I recall this scheme isn't / shouldn't be generated for dependencies.

I just picked a random repo that seems similar in that it

- has a dependency
- has no embedded `.xcodeproj` or `.xcodeworkspace`
- has no `scheme:` set in `.spi.yml`

i.e. a project that should be structurally equivalent to TextFormation. [Runestone](https://swiftpackageindex.com/simonbs/Runestone) seems to fit that bill.

So here's `xcodebuild -list -json` for Runestone:

```json
{
  "workspace" : {
    "name" : "Runestone",
    "schemes" : [
      "Runestone"
    ]
  }
}
```

None of its dependencies show up. There's no `*-Package` scheme at all.

I suspected that perhaps the custom target logic in TextFormation's `Package.swift`

```swift
let swiftSettings: [SwiftSetting] = [
	.enableExperimentalFeature("StrictConcurrency")
]

for target in package.targets {
	var settings = target.swiftSettings ?? []
	settings.append(contentsOf: swiftSettings)
	target.swiftSettings = settings
}
```

file might mess with scheme autogeneration and so I removed it (from a fresh checkout, to avoid caching issues). Still, Xcode lists all four schemes, as above. I have no idea why it's generating these schemes here and not for Runestone.

Moreover, I now wonder and worry what it does for other repos.

I think there are a few things to consider here:

1. Should we deploy the hack of looking for a clone URL base name match with a scheme name? If so, how lenient should be be here? Obviously case insensitive but what about prefixes like `swift-` or suffixes like `-iOS` which we do see frequently. That's a nice looking hole and I'm sure there's a rabbit at the end of it.
2. Do we have a (much) bigger problem here where we're building the wrong schemes in some/many cases? (NB: of 6964 packages that have `Package.resolved` reported in, 3965 (57%) have no dependencies. So a good chunk are safe by default. Runestone indicates that even among those with dependencies there are some/many that will be ok.)
3. How can we get a better view of the problem so we can decide how to fix it?
4. Can we get some info on how Xcode autogenerates schemes?

It's tempting to hack something together along the lines of 1) but our heuristics are getting messier and messier and it might be better to hold off.

An immediate fix for Matt's repo is for it to add a `scheme: TextFormation` entry to its `.spi.yml` file to ensure we do the right thing.

In order to figure out how big a problem we've got, we could do the following:

- capture the `xcodebuild -list -json` output and send it with the build report
- also send the scheme we've picked (via heuristics or an `.spi.yml` override)

This would allow us to run a full analysis across all packages and see how well this is working.

I'm leaning towards spending the effort on 3. rather than patch this over via 1.

We should also try and get in touch with someone on the Xcode team to find out about scheme autogeneration so there's less guesswork on our part (4.). I vaguely recall talking to a couple of folks very early on when creating the build system but this was never any formal documentation, more along the lines "this should work".

**Comment by mattmassicotte** [comment]
TextStory itself is special, in that it has multiple targets. I *think* Xcode will only auto-generate schemes for package dependencies that have multiple targets. Also, I believe the "-Package" scheme is only present in that situation as well. But I'm not 100% sure about either of those things.

I *think* what you need to do is pull out the package `name` field from the Package.swift file. From there, you list the schemes. If there is a `name-Package` you build that. Otherwise, you build `name`.  Could that work?

**Comment by finestructure** [comment]
I think that might be best, yes. It would mean another `dump-package` in the builder (which triggers package resolution) but it shouldn't actually be that bad, because `xcodebuild -list` _also_ triggers a package resolution. The only problem I can see is that they don't share the "resolution cache".

I'll give that a go, that's certainly a more sensible approach that peeking at the URL and feels like it might solve the whole problem without adding more instrumentation. (However, that's perhaps still a good idea to do at some point.)

**Comment by finestructure** [comment]
Fixed here: https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/262

- [ ] deploy

**Comment by finestructure** [comment]
This is now deployed. I believe you've actually fixed the visionOS build now, haven't you @mattmassicotte ? Let me know if not and I'll retrigger builds on main to correct the compatibility matrix!
