### ISSUE TITLE
XCFramework Archive Failed 

### ISSUE THREAD

**Issue by ManikantaDG** [SwiftPackageIndex/SwiftPackageIndex-Server#2956]
Hi Team, 

My XCFramework is unable to archive due to the SVGKit errors, and I am using the SVGKit SPM, whose version is 3.x. 

It occurs in the below error message while generating the XCFramework

"SwiftVerifyEmittedModuleInterface normal arm64 Verifying\ emitted\ module\ interface\ SVGKitSwift.private.swiftinterface /Users/d.manikanta/Library/Developer/Xcode/DerivedData/CardSuiteExperience-fhrvnrnletoqshdhvkiiwlihdkzt/Build/Intermediates.noindex/DependentBuilds/SVGKit.build/Debug-iphoneos/SVGKitSwift.build/Objects-normal/arm64/SVGKitSwift.private.swiftinterface (in target 'SVGKitSwift' from project 'SVGKit')"

Kindly help me with the fix. 

Please find the attached screenshots for your reference.

<img width="1239" alt="Screenshot 2024-03-19 at 7 49 05 PM" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/14157141/68d4c64e-faba-4c89-aa6b-2a37155b6f53">

<img width="1239" alt="Screenshot 2024-03-19 at 7 49 05 PM" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/14157141/a7a34f88-086e-4068-812d-71d53b7ab0f3">

Regards,
Manikanta DG.
8971446219.

**Comment by daveverwer** [comment]
Hi @ManikantaDG, and I'm sorry you're seeing problems with SVGKit.

Unfortunately, we don't support the packages here directly and we do not maintain the SVGKit library. This issue is better reported over at the https://github.com/SVGKit/SVGKit repository.

I'll close this, but please feel free to re-open it if it is indeed related to Swift Package Index and I misunderstood 👍 Good luck with your issue!
