### ISSUE TITLE
Improve parsing/detection of Swift language versions

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#303]
See https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/300#issuecomment-640104378

**Comment by daveverwer** [comment]
This is an interesting problem as we now have two potentially different sources of truth for the manifest, that both change over time (through the history of tags).

I don't *think* we want to parse the full package/product information out of a `Package@swift-4.2.swift` file, would it just be used to indicate compatibility with Swift 4.2, regardless of what's declared in the `swiftLanguageVersions` property in `Package.swift`?

But then, this looks really bad if there's a `Package@swift-4.2.swift` file, but no `swiftLanguageVersions` in the `Package/swift` then the package page would show *only* compatibility with Swift 4.2, which is almost certainly not true as the package author would not have created a new `Package.swift` file if not to support Swift 5.

@MaxDesiatov how would you see parsing of this file affecting your package listings?

**Comment by MaxDesiatov** [comment]
I imagine if this file isn't parsed, some of my packages won't be shown as supporting 4.2? And as I said in the other issue, I don't think that explicitly filling in `swiftLanguageVersions` is a good idea. For example, my packages support Swift 5.3, but what if I forget to add that version to the `swiftLanguageVersions` array after 5.3 is released? I'd rather omit that altogether so that the package always stays forward compatible with all versions that are higher than the version specified in the manifest version header.

And this is not specific to `Package@swift-4.2.swift`, there aren't just two sources of truth, but potentially more. You can have as many of these manifests as you want for each version. For example 5.3 adds conditional targets, so I could have three manifest files: basic `Package@swift-4.2.swift` to support people with 4.2, `Package@swift-5.0.swift` because the `platforms` stanza is only available in 5.0, and then `Package.swift` with 5.3 in its header to support conditional targets.

I know it's hard to support well in SPI, but this is the way that things are now, especially for packages that want to maintain broad backward and forward compatibility.

**Comment by daveverwer** [comment]
> And this is not specific to `Package@swift-4.2.swift`, there aren't just two sources of truth, but potentially more. You can have as many of these manifests as you want for each version. For example 5.3 adds conditional targets, so I could have three manifest files: basic `Package@swift-4.2.swift` to support people with 4.2, `Package@swift-5.0.swift` because the `platforms` stanza is only available in 5.0, and then `Package.swift` with 5.3 in its header to support conditional targets.

Yep, I think implicit in this issue is to parse `Package@swift-XXX.swift` files. 

But would you actually want to parse out the data from those files, or just use them as an indication of version support? For example, when we add dependencies or adding a list of products to SPI package pages. Would you see that data be split by the different versions of Swift? It quickly gets quite complicated, not to mention hard to display.

This is incredibly valuable feedback Max, thank you so much for your time on it.

**Comment by MaxDesiatov** [comment]
Yeah, indicating version support should be enough actually. So maybe there's no need to parse all of the manifests, just checking whether those are present should work, at least initially.

Thanks for reading my comments! I honestly don't know if my feedback is representative here, these are probably just edge cases that the vast majority of the packages don't have to deal with. 🙂

**Comment by daveverwer** [comment]
Thank you, Max.

@finestructure I also changed the title of this issue a little to track the general improvement of detecting Swift language versions, as opposed to being specifically about the one issue.

**Comment by orta** [comment]
I think this one is particularly important on the long term given that the build matrix for an SPM is pretty complex, a single SPM package can:

 - support many versions of swiftlang
 - support many OS/targets
 - support swift different tools versions

Trying to get all that info accurately and automatically is something you'll want early on as things you can build on

**Comment by daveverwer** [comment]
Yep, Sven and I have been talking a *lot* about this problem in the last week. 🤔

**Comment by daveverwer** [comment]
Closing as [Swift version and platform compatibility through the build processing system](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/projects/4) is imminent.

To your point @orta, we agree 👍

> I think this one is particularly important on the long term given that the build matrix for an SPM is pretty complex, a single SPM package can:
> 
> * support many versions of swiftlang
> * support many OS/targets
> * support swift different tools versions
> 
> Trying to get all that info accurately and automatically is something you'll want early on as things you can build on

This is going live in the next few days. Examples:

* https://staging.swiftpackageindex.com/finestructure/Rester
* https://staging.swiftpackageindex.com/Quick/Nimble

Forgive the missing boxes in some of those, we're processing builds on production right now ready for launch and filling in data on staging isn't a priority.

**Comment by orta** [comment]
great work
