### ISSUE TITLE
Blake2 by Tesseract seems to build quite often

### ISSUE THREAD

**Issue by hassila** [SwiftPackageIndex/SwiftPackageIndex-Server#3080]
I've seen it by accident many times in the build monitor and it seems it is rebuilt even though it was 8 months since the last commit?

<img width="931" alt="image" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/8501048/8c171f19-7191-4495-b144-7264fb1247e2">

**Comment by hassila** [comment]
<img width="906" alt="image" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/8501048/751ae27e-58d7-41d1-8cdf-25cc9777132e">

**Comment by finestructure** [comment]
This is an artefact of our build downscaling for packages that have proven problematic in the past.

Blake2 is a package that didn't pass builds for us in the past. What's worse is that it used up the full quota of 10mins we give every build and thus was a huge blocker whenever it hit our system - essentially locking everything down for 10mins. Since we retry builds that time out this happened every few hours when the package came around again for retry.

We've therefore had to downscale it to 0 in our build system, i.e. while it has builds scheduled and they appear to be running all the builder does when it sees such a package is short-circuit and ignore it, saving us previous build time.

We could perhaps avoid having these packages come around again for a retry but that would complicate matters should we want to lift a "downscale ban".

Does that make sense?

**Comment by finestructure** [comment]
Definitely appreciate the shout out! It's easy to miss things like that and it helps a lot if folks keep their eyes open :)
