### ISSUE TITLE
Missing packages in author's package collection

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#3091]
When I read this yesterday, I thought you were referring to the [`packages.json`](https://github.com/SwiftPackageIndex/PackageList/blob/main/packages.json) file in our PackageList repository.

The `collection.json` file is automatically generated and should include all the three packages listed on your author page. I'll convert this into an issue and take a look. Thanks for the report!

_Originally posted by @finestructure in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/3089#discussioncomment-9566581_

**Comment by finestructure** [comment]
https://swiftpackageindex.com/mesqueeb

<img width="753" alt="Screenshot 2024-05-27 at 08 12 22" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/a3bccbc9-5ae6-4f72-b39c-b7168cfffb44">

<img width="842" alt="Screenshot 2024-05-27 at 08 17 46" src="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/65520/d0ac3ea2-56ca-4502-a113-ea18c93936bb">

**Comment by finestructure** [comment]
Ah, I see what the problem is. Packages in a collection must have a release tag. The two missing packages don't have any, that's why only CaseAnything is in the collection.

Does that help, @mesqueeb?

**Comment by mesqueeb** [comment]
@finestructure thanks! sorry I didn't come back to you before. But after I properly started generating github releases, it's been fine.

albeit, the refreshing of `collection.json` after a new version is released is a bit slow imo... It'd be lovely if there was a URL the developer could just access to manually refresh it. Eg. adding a `?refresh` behind the `collection.json` URL to manually force the file will get generated over the next minute would be so cool!

Should I open a new issue or discussion for this or just leave it?

**Comment by daveverwer** [comment]
Unfortunately it's not quite that simple. We have processes *constantly* refreshing package metadata and discovering new package versions, but with 7,500+ packages to refresh, it takes several hours for each individual package to wait its turn for an update.

We may one day implement an API where package authors can ping a URL to notify us of a release to put that package to the top of the queue, but it's not something we are actively looking at right now. I'll start a discussion about it so that we have somewhere to point people if this issue comes up again.

**Comment by daveverwer** [comment]
Tracked here https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/3165
