### ISSUE TITLE
"Broken" links in README

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#3339]
I noticed that two links to SPI pages in @mattmassicotte's [MainOffender](https://swiftpackageindex.com/mattmassicotte/MainOffender) package show the broken link icon on our package page:

<img width="776" alt="Screenshot 2024-08-27 at 11 05 58" src="https://github.com/user-attachments/assets/936c2c77-f06d-4907-890c-325b324f21ab">

The links aren't really broken (well, the documentation one is a 404 but that's because Matt optimistically linked to it but hasn't yet added an `.spi.yml` file to generate docs 🙂), it's just that the badge isn't loading.

I suspect it's due to the way the links are set up:

```markdown
[![Build Status][build status badge]][build status]
[![Platforms][platforms badge]][platforms]
[![Documentation][documentation badge]][documentation]
```

which are resolved at the bottom of the file like so:

```markdown
[build status]: https://github.com/mattmassicotte/MainOffender/actions
[build status badge]: https://github.com/mattmassicotte/MainOffender/workflows/CI/badge.svg
[platforms]: https://swiftpackageindex.com/mattmassicotte/MainOffender
[platforms badge]: https://img.shields.io/endpoint?url=https%3A%2F%2Fswiftpackageindex.com%2Fapi%2Fpackages%2Fmattmassicotte%2FMainOffender%2Fbadge%3Ftype%3Dplatforms
[documentation]: https://swiftpackageindex.com/mattmassicotte/MainOffender/main/documentation
[documentation badge]: https://img.shields.io/badge/Documentation-DocC-blue
```

The links display correctly on Github:

<img width="783" alt="Screenshot 2024-08-27 at 11 11 15" src="https://github.com/user-attachments/assets/48c5c4bd-f031-4d9c-bedd-0e08b062e240">

**Comment by daveverwer** [comment]
The links are fine, it's the images used as links that are failing to load.

![Screenshot 2024-08-27 at 10 19 36@2x](https://github.com/user-attachments/assets/534beecd-8ee5-457d-b19a-e4a59edd8f4c)

GitHub are replacing the actual image link with a link to `camo.githubusercontent.com`, presumably caching the images in case shields.io goes down. I'm then guessing they refuse to serve that image if the page containing it is not being served from github.com.

We have a mechanism to also cache images as we already do it for images where GitHub give us an image gated with a token that expires 5 minutes after the request for the README happens. We should move these images to that same mechanism. Image tags with a `data-canonical-src` attribute might be a good place to start to find a full set of images affected, but I'll check that by looking at the README data a bit more closely when I fix this.

**Comment by daveverwer** [comment]
Yes, this is as I first suspected. If you `curl` that image URL it's a 403:

![Screenshot 2024-08-27 at 12 35 38@2x](https://github.com/user-attachments/assets/c77c84bc-cb44-41bd-957e-d5ef4767a690)

This must be a new measure from GitHub as we already have more than 21,000 images across 4,700 packages. These are mainly our shields.io badges (16,000 of the 21,000). We would have noticed that many broken images, so this must be new.

My worry if we cache these is whether GitHub will use a consistent hash in the `camo` URL. My fear is that it’s a hash of the URL, and since the shields.io URL changes every time compatibility changes, we would either need to implement the deletion of old cached images or face an ever-growing AWS bill.

I think a better solution for this one is not to add these to our caching process. That process should still remain, but only for the images it currently processes, which are the ones hosted *by* GitHub but which have the JWT proetcting them.

These images are not hosted by GitHub and we have the source URL in the `data-canonical-src` attribute. We should just “undo” the GitHub caching and replace the `camo` GitHub URL with the original one.

**Comment by daveverwer** [comment]
Looks good now it's deployed.

![Screenshot 2024-08-28 at 08 51 23@2x](https://github.com/user-attachments/assets/aeed3cea-27f7-4bc2-8720-ed187dbeb5c3)

**Comment by mattmassicotte** [comment]
Sorry for making your lives complicated! But, love that you dug into it and figured this all out.

**Comment by daveverwer** [comment]
It wasn't you at all! It was a change on GitHub's side that eventually affected every single README, yours was just one of the first to be affected.

I'm glad it was an easy one to work around 👍
