### ISSUE TITLE
--symbol-graph-minimum-access-level is not working for swift-mmio

### ISSUE THREAD

**Issue by Kyle-Ye** [SwiftPackageIndex/SwiftPackageIndex-Server#3374]
The latest main branch of swift-mmio (https://swiftpackageindex.com/apple/swift-mmio/main/documentation/svd2swift) still has the internal symbol.

> https://github.com/apple/swift-mmio/pull/118

And I can't get enough information from the log to continue investigating.

https://swiftpackageindex.com/builds/4046999D-F3D9-40C6-B7AC-19DEBF6DFE7E

**Comment by finestructure** [comment]
Looking at the overview I see that the `main` branch docs are still being generated with Swift 5.10. Only the `0.1.0-pre1` branch is opting into Swift 6 via the

```yml
      swift_version: 6.0
```

key.

![CleanShot 2024-09-10 at 11 44 05@2x](https://github.com/user-attachments/assets/b0e9d933-ee8e-4bec-a6ab-18bcb17076da)

If it's working for that tag you should also opt into Swift 6 on the `main` branch.

**Comment by finestructure** [comment]
I case it's not clear, the little document icon indicates which builds generated docs:

![CleanShot 2024-09-10 at 11 47 18@2x](https://github.com/user-attachments/assets/696a4fad-47a5-4451-9291-bcbf020e21e0)

**Comment by Kyle-Ye** [comment]
I am still confused about this.

1. This flag does not require Swift 6, only the latest version of swift-docc-plugin is needed.
3. I have checked the documentation on 0.1.0-pre1 and main, as well as the build logs of documentation build. The documentation still contains internal symbols and I am unable to obtain valuable compilation command parameters from the logs to further troubleshoot the issue.

**Comment by finestructure** [comment]
The command we're essentially running is

```
swift package
--allow-writing-to-directory
$outputPath
generate-documentation
--emit-digest
--disable-indexing
--output-path $outputPath
--hosting-base-path $hostingBasePath
--source-service github
--source-service-base-url https://github.com/$owner/$repo/blob/$reference
--checkout-path $checkoutPath
--target target
--symbol-graph-minimum-access-level public
```

If you run this locally, does it produce an archive with the expected symbol visibility?

**Comment by finestructure** [comment]
Other than that I can only note that there are no errors or warnings regarding documentation generation in the logs, so it's hard to diagnose any issues unfortunately.

**Comment by finestructure** [comment]
One thing perhaps worth trying is specifying the parameter as `--symbol-graph-minimum-access-level=public`.

**Comment by finestructure** [comment]
I've generated a doc set with our process for current `main` (`4357d917a0c746ffe2a95d5a1c406095b5389c00`) but I can't really tell if it's a "good" doc set or not, because I have no local setup to actually view it.

There must be a way to tell from the archive content (some of the symbol json files) whether it's ok or not. Or to view it without having to host the whole thing somewhere.

I've tried running the `preview-documentation` command and then replacing the contents of the `docs` directory but that doesn't work, because the docs generated via our process have different base paths and I just get a blank page.

I'm attaching the archive below in case you have a way of telling the difference.

[swift-mmio-docs-main.zip](https://github.com/user-attachments/files/16959754/swift-mmio-docs-main.zip)

**Comment by finestructure** [comment]
Actually, I think I see the difference:

```
❯ ls -l docs/data/documentation/svd2swift/
total 48
-rw-r--r--@ 1 sas  staff  10839 11 Sep 09:41 usingsvd2swift.json
-rw-r--r--@ 1 sas  staff  11690 11 Sep 09:41 usingsvd2swiftplugin.json
```

vs

```
❯ ls -l swift-mmio-docs-main/data/documentation/svd2swift/
total 240
drwxr-xr-x  17 sas  staff    544 11 Sep 09:29 accesslevel/
-rw-r--r--   1 sas  staff   6131 11 Sep 09:29 accesslevel.json
drwxr-xr-x   9 sas  staff    288 11 Sep 09:29 exportcontext/
-rw-r--r--   1 sas  staff   8117 11 Sep 09:29 exportcontext.json
drwxr-xr-x   9 sas  staff    288 11 Sep 09:29 exportoptions/
-rw-r--r--   1 sas  staff   8101 11 Sep 09:29 exportoptions.json
-rw-r--r--   1 sas  staff   1858 11 Sep 09:29 fileheader.json
drwxr-xr-x   5 sas  staff    160 11 Sep 09:29 indentation/
-rw-r--r--   1 sas  staff   3712 11 Sep 09:29 indentation.json
drwxr-xr-x   4 sas  staff    128 11 Sep 09:29 input/
-rw-r--r--   1 sas  staff   3000 11 Sep 09:29 input.json
drwxr-xr-x   5 sas  staff    160 11 Sep 09:29 inputreader/
-rw-r--r--   1 sas  staff   3944 11 Sep 09:29 inputreader.json
drwxr-xr-x   5 sas  staff    160 11 Sep 09:29 output/
-rw-r--r--   1 sas  staff   3757 11 Sep 09:29 output.json
drwxr-xr-x  11 sas  staff    352 11 Sep 09:29 outputwriter/
-rw-r--r--   1 sas  staff   7764 11 Sep 09:29 outputwriter.json
drwxr-xr-x  12 sas  staff    384 11 Sep 09:29 svd/
-rw-r--r--   1 sas  staff   4024 11 Sep 09:29 svd.json
drwxr-xr-x  45 sas  staff   1440 11 Sep 09:29 svd2swift/
-rw-r--r--   1 sas  staff  18311 11 Sep 09:29 svd2swift.json
drwxr-xr-x   7 sas  staff    224 11 Sep 09:29 svd2swifterror/
-rw-r--r--   1 sas  staff   4271 11 Sep 09:29 svd2swifterror.json
drwxr-xr-x   5 sas  staff    160 11 Sep 09:29 svdexportable/
-rw-r--r--   1 sas  staff   6868 11 Sep 09:29 svdexportable.json
drwxr-xr-x   6 sas  staff    192 11 Sep 09:29 swift/
-rw-r--r--   1 sas  staff   2387 11 Sep 09:29 swift.json
-rw-r--r--   1 sas  staff  10839 11 Sep 09:29 usingsvd2swift.json
-rw-r--r--   1 sas  staff  11690 11 Sep 09:29 usingsvd2swiftplugin.json
```

**Comment by Kyle-Ye** [comment]
> Actually, I think I see the difference:

Yeah. That's the bug here.

If swift-docc-plugin has identified "--symbol-graph-minimum-access-level" correctly, it should not produce internal symbol for `svd2swift`. (The extra ones in your documentation/svd2swift folder)

**Comment by Kyle-Ye** [comment]
Pipeline:
swift-docc-plugin -> trigger SwiftPM to build and extract the symbols.

If you pass --verbose to swift-docc-plugin call, you can see the full docc command.

eg.
```swift
swift package \
--disable-sandbox \
--allow-writing-to-directory \
./docs \
preview-documentation \
--emit-digest \
--disable-indexing \
--output-path ./docs \
--target SVD2Swift \
--symbol-graph-minimum-access-level public \
--verbose

# Output information in console
...
symbol graph options: 'SymbolGraphOptions(minimumAccessLevel: PackagePlugin.PackageManager.SymbolGraphOptions.AccessLevel.public, includeSynthesized: true, includeSPI: false, emitExtensionBlocks: true)'
...
docc invocation: '/Applications/Xcode-15.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc preview /Users/kyle/tmp/swift-mmio/Sources/SVD2Swift/Documentation.docc --emit-digest --fallback-display-name SVD2Swift --fallback-bundle-identifier SVD2Swift --additional-symbol-graph-dir /Users/kyle/tmp/swift-mmio/.build/arm64-apple-macosx/extracted-symbols/swift-mmio/SVD2Swift --output-path /Users/kyle/tmp/swift-mmio/docs --fallback-default-module-kind Command-line Tool'
...
```

1. Check the SymbolGraphOptions log information in you `swift-docc-plugin` verbose call.
2. Check `SVD2Swift.symbols.json` in additional-symbol-graph-dir.

It should be something like the following with empty symbols

```json
{"metadata":{"formatVersion":{"major":0,"minor":6,"patch":0},"generator":"Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)"},"module":{"name":"SVD2Swift","platform":{"architecture":"arm64","vendor":"apple","operatingSystem":{"name":"macosx","minimumVersion":{"major":10,"minor":15}}}},"symbols":[],"relationships":[]}
```

**Comment by finestructure** [comment]
This is baffling. We're clearly passing along the flags correctly, because `--verbose` is taking effect. Yet `--symbol-graph-minimum-access-level public` is clearly being ignored:

```
🖥️ env DEVELOPER_DIR=/Applications/Xcode-15.4.0.app xcrun swift package --allow-writing-to-directory .docs/finestructure/swift-mmio/issue-3374 generate-documentation --emit-digest --disable-indexing --output-path .docs/finestructure/swift-mmio/issue-3374 --hosting-base-path finestructure/swift-mmio/issue-3374 --source-service github --source-service-base-url https://github.com/finestructure/swift-mmio/blob/issue-3374 --checkout-path /var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/873F8D4C-C9B2-4801-B00F-3705D0788AD2/checkout --target SVD2Swift --symbol-graph-minimum-access-level public --verbose
Extracting symbol information for 'SVD2Swift'...
symbol graph options: 'SymbolGraphOptions(minimumAccessLevel: PackagePlugin.PackageManager.SymbolGraphOptions.AccessLevel.internal, includeSynthesized: true, includeSPI: false, emitExtensionBlocks: true)'
```

Can you think of anything else that might be interfering?

I've made sure the docc-plugin version is constrained to the latest when appending the dependency:

```
package.dependencies.append(
    .package(url: "https://github.com/swiftlang/swift-docc-plugin", from: "1.4.3")
)
```

**Comment by finestructure** [comment]
Is there any chance that `preview-documentation` and `generate-documentation` are behaving differently? It's about the only difference I can see at the moment between these two tests we're comparing.

**Comment by finestructure** [comment]
The `docc` invocation doesn't contain any flags related to access level (but neither does it for yours):

```
docc invocation: '/Applications/Xcode-15.4.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/docc convert /private/var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/C5D10A1C-5F63-45E5-8744-2CCC518E3941/checkout/Sources/SVD2Swift/Documentation.docc --emit-digest --hosting-base-path finestructure/swift-mmio/issue-3374 --source-service github --source-service-base-url https://github.com/finestructure/swift-mmio/blob/issue-3374 --checkout-path /var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/C5D10A1C-5F63-45E5-8744-2CCC518E3941/checkout --fallback-display-name SVD2Swift --fallback-bundle-identifier SVD2Swift --additional-symbol-graph-dir /private/var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/C5D10A1C-5F63-45E5-8744-2CCC518E3941/checkout/.build/arm64-apple-macosx/extracted-symbols/checkout/SVD2Swift --output-path /private/var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/C5D10A1C-5F63-45E5-8744-2CCC518E3941/checkout/.build/plugins/Swift-DocC/outputs/intermediates/SVD2Swift.doccarchive --fallback-default-module-kind Command-line Tool'
```

**Comment by Kyle-Ye** [comment]
Yeah. The information goes into swift-docc-plugin and produce `SVD2Swift.symbols.json` in additional-symbol-graph-dir.

You need to debug swift-docc-plugin instead of swift-docc.

**Comment by finestructure** [comment]
> Can you ssh into your CI machine and using a local swift-docc-plugin to debug it directly?

That's not an option but also my integration test is running the exact same code as does the live service (and we can see that it produces the same result).

I can't think of anything else to try here but I'll leave the issue open in case we come up with other things to try.

**Comment by Kyle-Ye** [comment]
> ```
> 🖥️ env DEVELOPER_DIR=/Applications/Xcode-15.4.0.app xcrun swift package --allow-writing-to-directory .docs/finestructure/swift-mmio/issue-3374 generate-documentation --emit-digest --disable-indexing --output-path .docs/finestructure/swift-mmio/issue-3374 --hosting-base-path finestructure/swift-mmio/issue-3374 --source-service github --source-service-base-url https://github.com/finestructure/swift-mmio/blob/issue-3374 --checkout-path /var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/873F8D4C-C9B2-4801-B00F-3705D0788AD2/checkout --target SVD2Swift --symbol-graph-minimum-access-level public --verbose

Can you give me a full reproducible steps for your env? Otherwise I can't reproduce it.

eg. Send me the source directory of your swift-mmio or give the diff.patch compared with the latest main. (I assume you have modified the Package.swift otherwise there is no swift-docc-plugin dependency.)

I've give mine at here.

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3374#issuecomment-2340597139

**Comment by finestructure** [comment]
I'm attaching the checkout directory below, although I suspect it won't be of much use. I just ran _the same command as my integration test_ in it and it produces:

```
❯ env DEVELOPER_DIR=/Applications/Xcode-15.4.0.app xcrun swift package --allow-writing-to-directory docs generate-documentation --emit-digest --disable-indexing --output-path docs --hosting-base-path finestructure/swift-mmio/issue-3374 --source-service github --source-service-base-url https://github.com/finestructure/swift-mmio/blob/issue-3374 --checkout-path $PWD --target SVD2Swift --symbol-graph-minimum-access-level public --verbose
Building for debugging...
[1/1] Write swift-version-33747A42983211AE.txt
Build complete! (0.24s)
Building for debugging...
[1/1] Write swift-version-33747A42983211AE.txt
Build complete! (0.45s)
Extracting symbol information for 'SVD2Swift'...
symbol graph options: 'SymbolGraphOptions(minimumAccessLevel: PackagePlugin.PackageManager.SymbolGraphOptions.AccessLevel.public, includeSynthesized: true, includeSPI: false, emitExtensionBlocks: true)'
```

whereas my test produces

```
🖥️ env DEVELOPER_DIR=/Applications/Xcode-15.4.0.app xcrun swift package --allow-writing-to-directory .docs/finestructure/swift-mmio/issue-3374 generate-documentation --emit-digest --disable-indexing --output-path .docs/finestructure/swift-mmio/issue-3374 --hosting-base-path finestructure/swift-mmio/issue-3374 --source-service github --source-service-base-url https://github.com/finestructure/swift-mmio/blob/issue-3374 --checkout-path /var/folders/nk/tlpts6bs799038htr6rx1xnc0000gn/T/445584C3-528E-444D-AE10-0E9C3FCB7A2A/checkout --target SVD2Swift --symbol-graph-minimum-access-level public --verbose
Extracting symbol information for 'SVD2Swift'...
symbol graph options: 'SymbolGraphOptions(minimumAccessLevel: PackagePlugin.PackageManager.SymbolGraphOptions.AccessLevel.internal, includeSynthesized: true, includeSPI: false, emitExtensionBlocks: true)'
```

I'm baffled. The test is as follows and essentially ends up running a `Process` with the above command:

```swift
    func test_issue_3374() async throws {
        // https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2504
        let cloneURL = "https://github.com/finestructure/swift-mmio"
        let ref = "issue-3374"
        let pathFragment = try Github.url.parse(cloneURL).path
        try await generateDocs(cloneURL: cloneURL,
                               reference: ref,
                               platform: .macosSpm,
                               swiftVersion: .latestRelease) { tempDir in
            let docsDir = tempDir + "/checkout/.docs/\(pathFragment)/\(ref)"
            print("open \(docsDir)")
            let indexJSON = "\(docsDir)/index/index.json".lowercased()
            XCTAssertTrue(
                Foundation.FileManager.default.fileExists(atPath: indexJSON),
                "not found: \(indexJSON)"
            )
            let index = try XCTUnwrap(DocArchive.Index(path: indexJSON))
            XCTAssertEqual(index.interfaceLanguages.swift.map(\.path), [
                "/documentation/svd2swift"
            ])
            let jsonFiles = try await Current.shell.run(command: .ls("\(docsDir)/data/documentation/svd2swift"))
                .split(separator: "\n")
                .sorted()
            XCTAssertEqual(jsonFiles.count, 2)
            XCTAssertEqual(jsonFiles, ["usingsvd2swift.json", "usingsvd2swiftplugin.json"])
        }
    }
```

It's pointing to my fork to add the `--verbose` and trim the target list. You'll see that it's essentially the official `main` otherwise.

There must be something in the test's environment that prevents it from picking up the flag. We only pass a limited set up env variables, I wonder if it could be that?

[checkout.zip](https://github.com/user-attachments/files/16975153/checkout.zip)

**Comment by finestructure** [comment]
I'm working on extracting this into a standalone test that I can share. It's going to take a moment to do that unfortunately!

**Comment by finestructure** [comment]
I've pushed a standalone test repo here: https://github.com/finestructure/Issue3374

If you run the test it shows the problem:

![CleanShot 2024-09-18 at 11 38 40@2x](https://github.com/user-attachments/assets/fabb5375-3dad-4df0-b7b3-a9b8050229d8)

The underlying machinery is a stripped down version of what we run on our build machines and seems to reproduce the problem exactly as it does in production.

**Comment by Kyle-Ye** [comment]
1. The package is requiring Swift 6. But the `DEVELOPER_DIR` is hard coded as 15.4. I'm changing it into 16.0 and I believe it does not matter here.
2. I can reproduce it in your example. Thanks.

The next step I'm doing:

1. Replace the remote swift-docc-plugin dependency with my local one.
2. Try to debug it to figure out what's happening here.

**Comment by Kyle-Ye** [comment]
The arguments has passed in successfully at the beginning.

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/587d60c0-2b54-4124-bb83-092cf1885d32">

But when we actually consume it when symbol-graph generating in the end. It just gone.

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/5f22d1ad-7b4e-4678-a689-23b3492b076f">

**Comment by Kyle-Ye** [comment]
I might know the problem here.

It is 10 elements now.
```
▿ 10 elements
  - 0 : "--emit-digest"
  - 1 : "--disable-indexing"
  - 2 : "--output-path"
  - 3 : ".docs/finestructure/swift-mmio/issue-3374"
  - 4 : "--hosting-base-path"
  - 5 : "finestructure/swift-mmio/issue-3374"
  - 6 : "--target"
  - 7 : "SVD2Swift"
  - 8 : "--symbol-graph-minimum-access-level public"
  - 9 : "--verbose"
```

But it should be 11 elements as follows.

```
▿ 10 elements
  - 0 : "--emit-digest"
  - 1 : "--disable-indexing"
  - 2 : "--output-path"
  - 3 : ".docs/finestructure/swift-mmio/issue-3374"
  - 4 : "--hosting-base-path"
  - 5 : "finestructure/swift-mmio/issue-3374"
  - 6 : "--target"
  - 7 : "SVD2Swift"
  - 8 : "--symbol-graph-minimum-access-level"
  - 9 : "public"
  - 10 : "--verbose"
```

**Comment by Kyle-Ye** [comment]
What do you think of adding a logic of spliting the arguments by " " and flat them in SPI by `arguments.flatMap { $0.split(separator: " ") }.map { String($0) }`?

Anyway, I'll fix it on swift-mmio side via https://github.com/apple/swift-mmio/pull/122.

**Comment by finestructure** [comment]
Ah, that's great, well spotted!

I suspected something like this and that's why I suggested trying `--symbol-graph-minimum-access-level=public` [above](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3374#issuecomment-2340469164). 

I actually went ahead and tried it in my fork first thing - to no effect - and I think I know why now. I suspect the underlying command just silently ignores parameters it doesn't recognise rather than throw an error. It's really good to know that that's the case for future debugging sessions (although it would help if there was at least a warning).

I'll leave the issue open until we've verified the docs are correct with your upstream fix.

Thanks for your help fixing this!

**Comment by finestructure** [comment]
> What do you think of adding a logic of spliting the arguments by " " and flat them in SPI by `arguments.flatMap { $0.split(separator: " ") }.map { String($0) }`? Or should we give a warning here?

That's probably something I'll add, yes, just to remove that particular sharp edge. As I said, what would really help is a warning from the upstream commands (not sure which one that is - probably `docc`?) when this happens.

**Comment by Kyle-Ye** [comment]
> As I said, what would really help is a warning from the upstream commands (not sure which one that is - probably docc?) when this happens.

I believe it will land on swift-docc-plugin if it should have a warning.

I can add it for unrecognized warning here. What do you think about it? @d-ronnqvist

**Comment by d-ronnqvist** [comment]
> > As I said, what would really help is a warning from the upstream commands (not sure which one that is - probably docc?) when this happens.
> 
> I believe it will land on swift-docc-plugin if it should have a warning.
> 
> I can add it for unrecognized warning here. What do you think about it? @d-ronnqvist

We explicitly don't want to warn about unrecognized arguments in the DocC plugin because we have a feature where the plugin forwards all unrecognized flags to `docc`. This feature allows us to add new flags to DocC without updating the plugin and allows an older version of the plugin to be used with newer versions of DocC. 

The plugin documentation even has examples of flags that the plugin doesn't "recognize", like `--hosting-base-path` in [this section](https://swiftlang.github.io/swift-docc-plugin/documentation/swiftdoccplugin/publishing-to-github-pages#Generating-the-Documentation-Site).

**Comment by finestructure** [comment]
Is there a way a warning mode could be enabled? The problem is that _we_ are picking a certain combination of plugin and docc when we generate docs, which might be different to what _users_ are testing their setup with. If we don't get any warnings it's quite tricky for us to help diagnose the issue - and users have no chance to diagnose it themselves via our build logs (except @Kyle-Ye now 😆).

**Comment by finestructure** [comment]
I've deployed a fixed version and regenerated the docs:

![CleanShot 2024-09-19 at 11 36 03@2x](https://github.com/user-attachments/assets/adaa8112-54b8-4793-81e3-bae8b5fb0233)

**Comment by d-ronnqvist** [comment]
> Is there a way a warning mode could be enabled? The problem is that _we_ are picking a certain combination of plugin and docc when we generate docs, which might be different to what _users_ are testing their setup with. If we don't get any warnings it's quite tricky for us to help diagnose the issue - and users have no chance to diagnose it themselves via our build logs (except @Kyle-Ye now 😆) if it doesn't show any warnings.

If you're asking if the plugin could have an opt-in behavior where it warns about any "unknown" flags then the answer is yes, but it would cause a lot of noise since it would warn about all the passthrough flags. 

For example, in the example command from earlier:

> The command we're essentially running is
> 
> ```
> swift package
> --allow-writing-to-directory
> $outputPath
> generate-documentation
> --emit-digest
> --disable-indexing
> --output-path $outputPath
> --hosting-base-path $hostingBasePath
> --source-service github
> --source-service-base-url https://github.com/$owner/$repo/blob/$reference
> --checkout-path $checkoutPath
> --target target
> --symbol-graph-minimum-access-level public
> ```

these flags are "unknown" flags that the plugin forwards to DocC; `--emit-digest`, `--hosting-base-path`, `--source-service`, `--source-service-base-url`, and `--checkout-path`. I'm presuming that some subset of these would be present in every builds (at the very least to specify the base path) which would mean that a simple opt-in behavior to warns about any "unknown" flags would result in warnings for every project.

The way to remedy this would be to make the plugin aware of _all_ passthrough flags but this introduces two problems:
- Either each plugin version needs to be associated with a certain DocC version or every plugin version needs to be aware of all the different DocC flags for _all_ past DocC versions.
- Every time we add a new DocC flags we also need to release a new plugin version that knows of that flag.

If each plugin version is associated with a certain DocC version, then this effectively robs both you and the developer of their choice of combinations of DocC and Plugin. 

This leads me to think that the only way for both you and the developer to be able to chose a combinations of DocC and Plugin versions and not have a large amount of warning noise is to make the plugin know of all possible flags for all previous DocC versions. This is what I was referring to when I said that we wouldn't want to add this type of warning.

**Comment by finestructure** [comment]
That's unfortunate, thanks for the explanation, @d-ronnqvist ! I presume that not all flag are destined for `docc`, so it wouldn't be an option to let _it_ issue the warning when it eventually gets invoked.

Is there any way you can see how we could better surface issues with doc gen invocations?

For example, initially I didn't even know what result Kyle was looking for in the doc pages, because I didn't know how `--symbol-graph-minimum-access-level public` is reflected in the output. It seemed to be working fine to my eyes but didn't actually render as expected.

Perhaps one option would be to run with `--verbose` by default and look at the `symbol graph options`. But that's probably only one part of the info affected by flags.
