### ISSUE TITLE
Most recent release of package swedish-pnr is only partially picked up by the index

### ISSUE THREAD

**Issue by tancred** [SwiftPackageIndex/SwiftPackageIndex-Server#3414]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/Oops-AB/swedish-pnr

**Please explain what data is incorrect and what you expected to see**

The package index says the latest release is 1.0.3, the compatibility section too, listing Swift versions and platform for 1.0.3.

However, the most recent release is 1.1, which _has_ been picked up by the index in both the readme and the release notes.

**Comment by finestructure** [comment]
Thanks for the report, @tancred ! The problem is that strictly speaking `v1.1` isn't a Semantic Version compatible version. It would have to be `v.1.1.0`. We're considering making a chance to accept these abbreviated versions as well but it's a wide-ranging change and the cases where it's been problematic were very few, so we haven't looked into it yet.

If you tag your release `v1.1.0` it'll be picked up straight away.

**Comment by tancred** [comment]
Ah, I see! Thanks!
