### ISSUE TITLE
Baselines off slightly?

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#369]
Is it just me (and/or my browser) or are the icon baselines off a bit?

<img width="94" alt="Screenshot 2020-06-11 at 08 31 25" src="https://user-images.githubusercontent.com/65520/84352636-fcff9b80-abbd-11ea-9b15-9a69e45385cc.png">

Certainly the star seems to be sinking 😆

**Comment by daveverwer** [comment]
It's not just you, and I noticed that it's more visible with the star too. I've spent at least an hour trying to get this right and failed every time.

The only way I found to reliably do it is with flexbox. I did that in the License lozenge (which also had the same problem) but it's not possible to use that technique here as it would mean the icon was centred in the middle of the whole text block when it wraps to two lines.

**Comment by finestructure** [comment]
I now realise what a can of wyrms I've openened here and this is me slowly backing away 🤣

**Comment by daveverwer** [comment]
I'll leave it open as I'd like to look at it again one day... Or maybe someone better at CSS than me will come along. 🤞

**Comment by r-thomson** [comment]
You can manually move the icons into the right position by setting `vertical-align` with `em` as a unit.

**Comment by daveverwer** [comment]
@r-thomson this is amazing! Thank you.

I'm confident that I changed it to `baseline` several times while during my frantic attempts to fix it, but you know how it is when you're changing so much that the simple solution gets lost. 😬

It ended up being just as simple as setting `vertical-align` as `baseline`, no need for the `em`s. Thank you so much for your help. Fixed in #396.
