### ISSUE TITLE
Remove Google Analytics or ask user's permission 

### ISSUE THREAD

**Issue by MaxDesiatov** [SwiftPackageIndex/SwiftPackageIndex-Server#411]
I don't think that the current implementation is GDPR-compliant. I'd prefer the index to ask for user's permission before it starts gathering any analytics, or even loading GA scripts.

In general, I hope that GA wouldn't be needed at all, especially as you're not doing any conversion tracking, A/B testing etc. Aggregate traffic stats can be retrieved through server and CDN logs if needed.

**Comment by daveverwer** [comment]
Thanks for bringing this up Max.

So, as far as I was aware, our basic usage of Google Analytics complied with GDPR without a cookie popup or banner. I've looked into this in detail this morning, and you're right that it did not. There was a setting that needed updating, so I have just made that change.

I am not keen to remove analytics from this site, but I hope it goes without saying that we don't care about tracking individuals. I also understand the problems with Google having a comprehensive map of traffic on the internet, but I do want to have basic usage analytics over and above what Cloudflare gives us. As we expand this site, I want to be able to see what features are getting used, so I can see where we should dedicate effort. I've tried other analytics solutions Matomo specifically, but they are just not as good.

The changes I have made are as follows:

I have anonymised IP address data using Google Analytics built-in support for doing so. You can verify this on the site, but I've included a screenshot from Google Tag Manager with the setting active.

<img width="897" alt="Screenshot 2020-06-16 at 09 20 48@2x" src="https://user-images.githubusercontent.com/5180/84762246-79c9b580-afc2-11ea-8e93-11cdfe060b61.png">

I also changed the data retention period to its lowest value of 14 months, down from the default of 26 months. While this isn't necessary as part of GDPR, data over a year old is of limited use so we should not keep it.

<img width="378" alt="Screenshot 2020-06-16 at 09 36 54@2x" src="https://user-images.githubusercontent.com/5180/84762270-80582d00-afc2-11ea-8f00-35cd09f829cc.png">

We do not use any of Google Analytics's advertising-related features, and remarketing/retargeting is off by default (and I have not enabled it). No other third party analytics or trackers are in use (no social icons, social login, etc.) and I don't ever want to include those features. If (and it's a big if, because we don't have any plans to) we ever add user accounts to this site, it won't be using Google/Facebook/Twitter/etc. logins.

Finally, I think it's also worth talking about IP address logging elsewhere. We do not (currently) run requests through Apache or nginx which are both configured to log IP addresses by default. As far as I'm aware, Vapor does not by default make any HTTP logs, and we don't record any IP address information elsewhere. If we ever do change to running requests through a proxy, we will configure whatever proxy we choose not to log IP addresses.

Thanks again for bringing this up Max, it's worth talking about.

**Comment by MaxDesiatov** [comment]
Wouldn't it work better if this issue remains open until Vapor introduces HTTP logging by default, or someone enables a 3rd-party library for that in SPI, or a proxy is set up?

**Comment by daveverwer** [comment]
I left it open for a while after making my comment in case there were additional questions around it, but then closed it as I don't think there's any additional work needed at this point. 

While taking care of the privacy of users of the SPI will require constant work and attention, I'd rather only have issues in the backlog that actively require work, and I don't think there's anything else needed at this point. Please feel free to add things if you believe that not to be the case though!

I take this issue seriously, not because there's an open issue in the backlog, but because I take it seriously. I don't plan to ever include more analytics, trackers, or anything around that to the site, and that didn't change when I closed the issue. If Vapor adds HTTP logging, we'll remove the IP address not because it was mentioned here, but because it's the right thing to do, and it's the same with a proxy.

I know you don't owe us trust on this, but I can say that this is on my mind as I think about the development of this site, regardless of whether this issue is open or closed.

**Comment by MaxDesiatov** [comment]
>I don't think there's anything else needed at this point.

You've previously mentioned a proxy or possible HTTP logging in Vapor, wouldn't those be the remaining action points to be implemented that would allow collecting necessary analytics without GA and to keep the issue open until that's done? 

I appreciate you keeping this in mind, but as you can see from the reactions on Swift Forums and here, I'm not the only person concerned with sending our personal data to Google without our consent. I really like how SPI makes things decentralised, and SwiftPM itself it decentralised from the start, much in the spirit of the open web. It's really frustrating that while developing and using this software we still have to use services such as GA, feeding them more data, making big corporations such as Google stronger, undermining all of the decentralisation efforts. 😔

**Comment by daveverwer** [comment]
> > I don't think there's anything else needed at this point.
> 
> You've previously mentioned a proxy or possible HTTP logging in Vapor, wouldn't those be the remaining action points to be implemented that would allow collecting necessary analytics without GA and to keep the issue open until that's done?

Ah no, sorry, I think there's a misunderstanding here.

I didn't mean that those things would remove the need for Google Analytics, I was considering unexpected future privacy issues and saying how I'd deal with them. HTTP logging defaults in Apache and nginx log IP addresses by default (or they did last time I checked) and so I was mentioning it to make sure it was clear that I know this isn't just about Google Analytics.

As far as I know, Vapor don't have plans to make HTTP logging that includes an IP address default, and we have no plans to introduce a proxy. If we do need a proxy, we'll make sure to remove the IP address from the default logging configuration.

**Comment by daveverwer** [comment]
> I appreciate you keeping this in mind, but as you can see from the reactions on Swift Forums and here, I'm not the only person concerned with sending our personal data to Google without our consent. I really like how SPI makes things decentralised, and SwiftPM itself it decentralised from the start, much in the spirit of the open web. It's really frustrating that while developing and using this software we still have to use services such as GA, feeding them more data, making big corporations such as Google stronger, undermining all of the decentralisation efforts (in addition to giving away our privacy). 😔

I think where we disagree is that I don’t believe that now the IP address has been removed from GA, that this site is giving away personal data. We do not have any to give away, do we?

It’s true that Google can attach the Swift Package Index to  the profiles of this site’s visitors that it has, but I view the inclusion of this site in that profile as fairly inconsequential.

> undermining all of the decentralisation efforts (in addition to giving away our privacy

I think this is a very harsh way to think about it and all I can is say that I disagree that the inclusion of GA undermines all of the decentralisation efforts.

**Comment by lukeredpath** [comment]
Just chipping in here to mention that there's more to consider than just GDPR when dealing with analytics data - GDPR covers what data you collect and how you process it, but there's also the issue of cookies which is covered by PECR. Does Google Analytics work without cookies? 

If not, then it is still required to obtain a user's consent before installing any analytics or tracking cookies. The ICO have a good guide to this here:

https://ico.org.uk/for-organisations/guide-to-pecr/cookies-and-similar-technologies/

You may notice they have their own cookie control that pops up when you first visit the above link and note that analytics cookies are disabled by default (people need to opt-in).

I recommend Civic Cookie control, which is what the ICO use themselves. I used it on a recent client project and it was pretty easy to get up and running:

https://www.civicuk.com/cookie-control

**Comment by tkrajacic** [comment]
> I think where we disagree is that I don’t believe that now the IP address has been removed from GA, that this site is giving away personal data.

I cannot believe that you really believe this. Now only _you_ not seeing the IP addresses, but Google still gets them. And they still build their profile with all your visitors.

Further, it is beyond me how anyone can think that having GA on a site is still acceptable. You are handing data to Google, whether you think so or not, that is simply unacceptable.

When you say "we don't care about tracking individuals" you completely ignore the fact that Google still does. And you enable them. And yes, this has nothing to do with being compliant to some law, it is about having a moral obligation.

It is very simple: DO NOT GIVE GOOGLE ANY ACCESS. I am really shaking my head how someone can still defend this in the slightest. And I think Max wasn't remotely harsh enough.

If you want usage data from your users, sure, you have to ask them, but if you then hand the data to Google for that purpose you have already lost any moral credibility.

/rant over

**Comment by daveverwer** [comment]
Hi Thomas

I appreciate this is a subject that you have very strong opinions on, but the way you expressed them in that message is bordering on unacceptable. I’d ask you to please review the [code of conduct](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/main/CODE_OF_CONDUCT.md) for this repository before posting again.

Thanks
Dave

**Comment by tkrajacic** [comment]
I apologize for being rude. And while I can't comprehend this is still being discussed in the year 2020 I will harshly critique myself on my tone. The behavior of not removing GA is unacceptable on another level though that is beyond being rude. There is no excuse for that.
