### ISSUE TITLE
RSS releases - show release notes

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#421]
This would be a bigger task, as we’re not currently collecting release notes (if there are any, even), but it’d be particularly nice for the RSS feed to show you what changed at a glance inline in the feed.

**Comment by daveverwer** [comment]
If we need to get the release date to fix #414 we may be able to grab the release notes in the same API call.

**Comment by finestructure** [comment]
We have release notes in `versions.release_notes` in the db now, so this should be a fairly straightforward task now.

**Comment by daveverwer** [comment]
Technically, yes. It does need some careful placing into the package page though. Still a good issue to tackle, but the design aspect of this task isn't trivial.

**Comment by finestructure** [comment]
This is for the RSS feed though, not the package page.

**Comment by daveverwer** [comment]
Oops, so it is. 😵‍💫

**Comment by elfenlaid** [comment]
I'll have a look at it if everyone is okay

**Comment by daveverwer** [comment]
Sounds good to me! I also had a thought of how we can fit this into the current web design too, but that's for a different ticket. 

One thought I did have is that we are currently getting the release notes as plain text, meaning we'll have to process them through a Markdown parser. That's no problem, however, we'll potentially run into the same issues we had with README files where people are using GitHub flavoured markdown and relying on GitHub syntax highlighting etc... 

We found that for the GitHub README call, we can request rendered HTML instead of grabbing the plain text README. I wonder if that's possible for the release notes too? That would make us much more compatible with and also make the implementation of web release notes much easier in the future. 

The API documentation for how to fetch README updates [is here](https://docs.github.com/en/rest/reference/repos#get-a-repository-readme) and it's specifically the part where they reference 

If that's not possible, we may just want to use GitHub's Markdown API for rendering what we already have rather than using Ink for the same reasons I mentioned above. https://docs.github.com/en/rest/reference/markdown

**Comment by daveverwer** [comment]
Oops didn't mean to close it! 😬

**Comment by elfenlaid** [comment]
> We found that for the GitHub README call, we can request rendered HTML instead of grabbing the plain text README. I wonder if that's possible for the release notes too? That would make us much more compatible with and also make the implementation of web release notes much easier in the future.

I think I've found the right API:

<pre><code>
$ curl https://api.github.com/repos/SnapKit/SnapKit/releases/tags/5.0.1 \
  -H "Accept: application/<strong>vnd.github.html+json</strong>"

{
  "url": "https://api.github.com/repos/SnapKit/SnapKit/releases/19070543",
  "assets_url": "https://api.github.com/repos/SnapKit/SnapKit/releases/19070543/assets",
  ...
  <strong>"body_html": "..."</strong>
}
</pre></code>

So, I'll propagate it into `release.description` + `version.release_notes` and see how it would look like in RSS readers.

Also, as `api.github.com` can do the same trick for README, I can't stop to wonder why SPI fetches the web version of the README page 🤔

Maybe it can be optimized and loaded directly from Github from the front end side?

**Comment by daveverwer** [comment]
> Also, as `api.github.com` can do the same trick for README, I can't stop wondering why SPI fetches the web version of the README page 🤔

Because I didn't know the API worked like that when I implemented it 😬 Changing it is tracked as #1095
