### ISSUE TITLE
Fix Rollbar issue

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#526]
We’re accumulating rollbar issues at a rate of a couple hundred per day and are at 70% of quoate (renewing on July 28).

> Production
>
> Critical
>
> 455 occurrences: https://rollbar.com/finestructure/SPI-server/items/16/
server: duplicate key value violates unique constraint "idx_repositories_owner_name" (_bt_check_unique)
Status: Active
>
> 2 occurrences: https://rollbar.com/finestructure/SPI-server/items/20/
> Abort.500: Internal Server Error
> Status: Active

This started last Sunday around around 1pm UTC. I think it’s related to the bulk import. We may have had a number of those in the db under different urls and they clash once the current owner/repo are resolved.

Need to investigate and resolve this soon or we’ll use up our Rollbar quota.

**Comment by Sherlouk** [comment]
> We may have had a number of those in the db under different urls and they clash once the current owner/repo are resolved.

So we do now have prevention against URLs which redirect to another, but that was done after the bulk import.

Do we have any way of running a query to detect all the broken URLs?

Also do you have any ideas about how we could introduce some sort of auto-fix resolution? In this particular instance it's more complicated because the URL storage is in a git repo, not a database. 

If we had a query which returned all the duplicates, we could have some sort of API which returned this list? We might be able to then create a CI job which periodically checks, and as it'd be a trusted source it could automatically create the merge request for us using the GitHub API.

**Comment by daveverwer** [comment]
We don't have any of that yet, it's a manual process for now. I thought I had fixed the dupes manually after the import, but I had not. 🙄

Sven and I had a quick chat about this issue today and it's something we'd like to improve. I can include you in that group chat if/when we continue talking if you'd like?

**Comment by Sherlouk** [comment]
For sure invite me in, I just slipped momentarily into my work's resiliency brain 😅  "Auto-fixes for everything!"

**Comment by daveverwer** [comment]
Oop 

<img width="582" alt="Screenshot 2020-07-17 at 13 35 47@2x" src="https://user-images.githubusercontent.com/5180/87786792-7e3bf500-c832-11ea-9282-d80167245c60.png">

**Comment by finestructure** [comment]
Housekeeping - this has long been fixed :)
