### ISSUE TITLE
Add a build deny list (package and/or version level)

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#617]
See https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/664 for one reason we may want this.

**Comment by daveverwer** [comment]
If/when we do this, we need to think about how we make this information obvious to someone browsing the package. I think it probably fits on the full builds page somewhere rather than the main package page, because it's mainly going to be used for those troublesome packages with Swift 5.1, so nothing critical, but we need to think about it.

**Comment by finestructure** [comment]
Deployed now via downscaling. There's currently no distinct state for this. A build will simply be pending and then unknown again after being "garbage collected", cycling between the two until it is actually built.
