### ISSUE TITLE
Add an intermediate search results page

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#635]
There should be an intermediate search results page that lives on the URL:

`/search?query=[query]&page=[page]`

The rough layout for the page can be seen in #636. 

The "paging" control at the bottom should have previous/next links (if relevant for the page number) and then a list of pages. It's almost certainly not necessary to do the "..." thing as pictured because I can't think that there would ever be more than a few pages of results. So, the numbers at the bottom are simply a list of pages that cover all possible search results. Those link to the search page again with the `page` parameter specified above.

Each page should have 20 results listed (but let's make this easily tweakable as we implement this as we'll want to play with what feels right).

Each search result should include the following:

* Package Name
* Package Description
* Package Identifier (For example `daveverwer/LeftPad`)

**Comment by finestructure** [comment]
Pagination is a little trickier due to the way we're running our search query. Normally we could just use

```swift
app.get("planets") { req in
    Planet.query(on: req.db).paginate(for: req)
}
```

but since our search is not run through a Vapor `Model`, we can't use this.

It shouldn't be hard to add pagination via `LIMIT` and `OFFSET` to the existing queries but the question is if we really want to / need to do that. Currently we're imposing a hard limit on 20 results on search, because it's for the drop down, which we presumably want to keep unchanged.

However, I wonder if we shouldn't just make that a softer limit that we keep at 20 for the drop down and say 40 or so (two pages max) for the search page. Then we simply do pagination on the Swift side by partitioning the results, rather than messing with the SQL query.

It depends a bit how "deep" we want search to be but I don't feel like more than a few dozen results are going to be terribly useful. What do you think?

**Comment by finestructure** [comment]
One remaining problem with our pagination is that we don't have a result total. I.e. we can't build a list of pages unless we also run an unconstrained `count` query.

**Comment by daveverwer** [comment]
I'd be 100% OK with losing the result total.

**Comment by finestructure** [comment]
I've thought about this some more and I don't believe we want to run two queries per search just to be able to build the paging control. (This would also affect the drop-down unless we special-cased it.) I think we should go back to fetching a static count (up to 40 or 60 results) and do some client side paging if need be.

**Comment by daveverwer** [comment]
Is it worth performance testing it before removing it? It could be that it's not a significant problem.

I think client-side paging (presuming you mean JavaScript paging) isn't really gaining anyone anything. I think if we're about to do that, then let's just return all 60 results and let people scroll. 

However, I'd love to get server-side paging in if we can.

**Comment by finestructure** [comment]
No, by client side page I didn't mean the web client, rather the "swift client side", i.e. after the fetch.
