### ISSUE TITLE
Tag move not being detected

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#693]
As discussed in #692, when packages have changes force pushed into their repositories, the default branch rebuilds without issues. 👍 This is good!

However, if the force pushed changes include re-targeting of a tagged version, we do not invalidate those builds.

Even though it's going to be unusual to have a force push re-target a tagged version, we should probably invalidate builds when this happens.

**Comment by finestructure** [comment]
We are definitely discarding the builds when we delete a version. The issue in this case seems to be that we still have the old association `1.0.0` → commit `3545d3d901f36f1e1a8c54af457ef3a26a704891` in the database.

`main` is pointing to `5477ac1e0fb8440f1e34d235c17fb922da98644c`.

So is the `1.0.0` tag on Github. For some reason the re-tag hasn't been picked up.

**Comment by finestructure** [comment]
Running this locally works just fine. But this executed a fresh clone because I hadn't run this before. I suspect there's an issue with the fetch. I'll extract the actual repo from our cache.

**Comment by finestructure** [comment]
Our cached repo isn't correctly updating with the new tag from upstream for some reason:

<img width="943" alt="Screenshot 2020-09-01 at 08 08 23" src="https://user-images.githubusercontent.com/65520/91800988-5b22a480-ec2a-11ea-9689-489dbfe625cb.png">

**Comment by finestructure** [comment]
The problem is that we're running `git fetch` and not `git fetch --tags` - which still wouldn't work but shows the error:

```
❯ git fetch --tags
From https://github.com/quickbirdstudios/XServiceLocator
 ! [rejected]        1.0.0      -> 1.0.0  (would clobber existing tag)
```

So the issue is that we don't see tags moving upstream because our fetch doesn't refresh them.

I'll add a pass to delete all local tags before fetching. I hope that's the last issue we'll have to deal with in this regard... I wish there was some canonical way to tell git to just accept the upstream as canonical.

For future reference, that got me to look up git repo mirroring and there is indeed [`git clone --mirror`](https://www.git-scm.com/docs/git-clone) and `git remote update`.

The problem with that is that `--mirror` implies `--bare` and that means the clone isn't a checkout. I.e. we'd need to make _another_ clone from that mirror. So while we'd save bandwidth and avoid the hassle of dealing with cruft we'd have to juggle with mirror and checkout locations. At this point it's probably just easier to deal with this issue specifically.

**Comment by daveverwer** [comment]
> would clobber existing tag

I have to think this error message was written by a British person 😂

**Comment by nasirky** [comment]
@finestructure and @daveverwer Thank you for the quick support and fix. Really appreciated 😄

**Comment by finestructure** [comment]
You're welcome! The patch is still giving us some trouble but I think your tag got updated before I had to roll it back 🙂

**Comment by finestructure** [comment]
Re-opened because we're rolling back #695 via #699

**Comment by finestructure** [comment]
Since tag deletion didn't work, I think the best way to deal with it is as follows:

- run `git fetch --tag`
- if this errors, ditch the directory and clone

It's just not worth fiddling with a repo at that point. It's sort of a cache invalidation signal and `git fetch` is really just a cache sync. If there's trouble we should ditch it instead of trying to patch it up.

**Comment by daveverwer** [comment]
I think this sounds great. It should also be very rare that this happens.
