### ISSUE TITLE
Suppress old revisions in firehose tweets for new packages

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#794]
(or see if we can skip new packages entirely - might not be possible)

<img width="592" alt="Screenshot 2020-11-18 at 12 36 34" src="https://user-images.githubusercontent.com/65520/99525931-cf9ff080-299a-11eb-8b17-33f280741b20.png">

**Comment by Sherlouk** [comment]
Yah I can see this being a bit confusing as we add more and more packages. I don't think we necessarily want to skip the package though - but instead change the message?

Rather than "owner just released package v1.0.0 - summary" it could be something more to do with "owner's package was just added - summary" or something.

I don't think the firehose has to necessarily be limited to new versions! New packages are just as valid and might pique the interest of onlookers.

Not sure the easiest/best way to detect a new package though! Check the created date on the package reference? Check how old the latest version is?
