### ISSUE TITLE
Use single markdown -> HTML converter throughout

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#828]
Bit of discussion in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/827 about this.

Currently we use Cmark+GFM for README markdown (on Package pages) and Ink for everything else (such as the privacy page). 

It'd be nice if eventually we removed the need for the Ink system to improve markdown compatibility and ensure we have consistency throughout the website.

This is not currently possible as we use the 'metadata' feature of Ink which allows for a small bit of key/value information at the top of a markdown file which is turned into the page title/description in MarkdownPage.swift. 

We'd need to reproduce this capability in the Cmark+GFM solution or approach it entirely differently. 

This is not a priority at this time but wanted to track it for future reference.

**Comment by daveverwer** [comment]
Thanks for logging this James!

There is another option here.

I eventually want to add a proper documentation site, which will remove the current FAQ based system, which people don't read because it's not very approachable. It was OK when we just had one FAQ, but now we have two 😬

The docs site, when we do it, will not be inside the main app. So this should be low priority.

**Comment by daveverwer** [comment]
We are now back to one Markdown processor as of #1090.
