### ISSUE TITLE
Populate targets for existing versions

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#872]
#871 adds support for persiting `targets` from the manifest file. However, this will only add them for newly created versions.

We need to explore how/if we can add `targets` to existing versions, in particular without incurring the cost of re-running all their builds.

**Comment by finestructure** [comment]
I’ve considered two general approaches to do this:

1. run a one-off process that selects versions without targets and creates the missing targets
2. integrate target creation for existing versions without targets into existing `analysis`

### Variant 1

The one-off process would work roughly as follows:
- we create a new command, similar to what we had to migrate the logs to S3
- this would be triggered manually in batches until we’ve updated all candidate versions
- these are fairly easy to select - it’s the versions without any targets
	- we’d potentially need to handle the case where a version really has no targets (if that is possible?), to avoid churning on it endlessly
- for these versions we load the manifest
- and create and save the targets
- by updating the version even in the case where there are 0 targets, we could handle the above case

Pro:
- relatively simple process
- we’ve used a similar mechanism before to move the logs and the manual execution worked without issues
- the process doesn’t interfere with the general target creation process for new versions and it doesn’t further complicate the analysis logic
Con:
- the process would need to be re-run whenever we have need to re-create targets for existing versions
	- this could for instance be the case if we added further fields to the table

### Variant 2

The continuous or analysis-integrate process would work as follows:
- extend the version diff to return not only added and deleted versions but also the kept versions
- these would need to be fed into a function that check if the target count of that version agrees with the target count of the manifest and update the targets accordingly

Pro:
- there would be no need to manage any processes when the target table changes, it would simply refresh, like almost all other tables do
Con:
- the implementation complicates an already quite complicated pipeline
	- for instance, the kept versions need to be routed through to the target count checker and the potential update futures need to be merged with all the other existing futures
- we’d need to query the targets table for its count for a particular version for every existing version on every analysis cycle
	- this is a lot of unnecessary db churn, because apart from the initial update after a schema change, and only that once, nothing will ever need to be done with that table again in this process step
	- many packages have quite a few existing versions, which we’d now read on every analysis cycle - this is what we optimised by doing version reconciliation. So while we wouldn’t be recreating the versions we’d still partially bring back a mechanism that scales with the total number of versions rather than just the version changes.

Since we’re unlikely to change the targets table very often I’d say we introduce the one-off process to create the targets for existing versions.

If we somehow find that we need this process more than once we can still integrate it into the analysis stage.

Also, if I remember correctly, we had some other table/fields that suffered from only being updated for new versions (what was it? tools-version?). We could potentially turn this whole updater into a mechanism that specifically deals with updating existing versions should this become a common theme.

**Comment by Sherlouk** [comment]
One consideration is that we might end up having to reprocess all Package.swift files when we do dependency analysis too. So a solution which is scalable for that could be handy (or might over complicate it).

**Comment by daveverwer** [comment]
This is also similar to the problem I brought up in #801. We're adding features to the analysis stage, and not using the results as the database only ever gets partially populated. The `tools-version` data is effectively always going to be useless, as already processed versions will never have data. There's a more immediate need to fix this for targets due to the package collection work, but the issue is fundamentally the same.

I wonder if it's worth stepping back and trying to find a way to run a full analysis pass without disconnecting version records from their build data. This will fix targets and tools version data, and as James says, when we add dependency visualisation, it will also need a full analysis pass.

To step back from the specific solutions for targets above and think about it more generally, I think it may have been a mistake to tie build records to the version_id. The build is really not tied to a version record, but the combination of a package and a commit hash. If we had keyed builds on some unique package identifier (probably URL) and a commit hash inside that repository's history.

Obviously keying anything on URL isn't perfect as URLs change all the time, we're already re-processing all builds when a package URL changes, so we'd be no worse off.

It feels like we're backing ourselves into a bit of a corner if we let the build data prevent us from ever doing a full analysis pass.

I understand that even the thought of doing a full build re-process is terrifying. It is for me too. It may be possible to avoid it, though. It would need downtime, and some dedicated scripts to grab the commit hashes for versions, but I think it's worth talking about?

**Comment by daveverwer** [comment]
Just to keep everyone up to date, Sven and I just chatted about this and we're going to have a mechanism where we can force an on-demand analysis pass that will initially fix targets and tools-version data, but which can be expanded to other data as we need it to.

We will not be doing my idea of detaching build data. 😬 It'll update records rather than replace them.

**Comment by finestructure** [comment]
> One consideration is that we might end up having to reprocess all Package.swift files when we do dependency analysis too.

Yes, that's definitely something to consider as well. In this particular case we may want to keep the dependencies on the package level though, because doing this per version might be a bit heavy.

**Comment by finestructure** [comment]
This is done now, see #801 for details.
